// Code generated by ent, DO NOT EDIT.

package signuplink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldCreatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldName, v))
}

// HashedCode applies equality check predicate on the "hashedCode" field. It's identical to HashedCodeEQ.
func HashedCode(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldHashedCode, v))
}

// ExpiresAt applies equality check predicate on the "expiresAt" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldExpiresAt, v))
}

// UserAgent applies equality check predicate on the "userAgent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldUserAgent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldIP, v))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContainsFold(FieldName, v))
}

// HashedCodeEQ applies the EQ predicate on the "hashedCode" field.
func HashedCodeEQ(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldHashedCode, v))
}

// HashedCodeNEQ applies the NEQ predicate on the "hashedCode" field.
func HashedCodeNEQ(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldHashedCode, v))
}

// HashedCodeIn applies the In predicate on the "hashedCode" field.
func HashedCodeIn(vs ...[]byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldHashedCode, vs...))
}

// HashedCodeNotIn applies the NotIn predicate on the "hashedCode" field.
func HashedCodeNotIn(vs ...[]byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldHashedCode, vs...))
}

// HashedCodeGT applies the GT predicate on the "hashedCode" field.
func HashedCodeGT(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldHashedCode, v))
}

// HashedCodeGTE applies the GTE predicate on the "hashedCode" field.
func HashedCodeGTE(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldHashedCode, v))
}

// HashedCodeLT applies the LT predicate on the "hashedCode" field.
func HashedCodeLT(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldHashedCode, v))
}

// HashedCodeLTE applies the LTE predicate on the "hashedCode" field.
func HashedCodeLTE(v []byte) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldHashedCode, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expiresAt" field.
func ExpiresAtEQ(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expiresAt" field.
func ExpiresAtNEQ(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expiresAt" field.
func ExpiresAtIn(vs ...time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expiresAt" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expiresAt" field.
func ExpiresAtGT(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expiresAt" field.
func ExpiresAtGTE(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expiresAt" field.
func ExpiresAtLT(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expiresAt" field.
func ExpiresAtLTE(v time.Time) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldExpiresAt, v))
}

// UserAgentEQ applies the EQ predicate on the "userAgent" field.
func UserAgentEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "userAgent" field.
func UserAgentNEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "userAgent" field.
func UserAgentIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "userAgent" field.
func UserAgentNotIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "userAgent" field.
func UserAgentGT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "userAgent" field.
func UserAgentGTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "userAgent" field.
func UserAgentLT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "userAgent" field.
func UserAgentLTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "userAgent" field.
func UserAgentContains(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "userAgent" field.
func UserAgentHasPrefix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "userAgent" field.
func UserAgentHasSuffix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "userAgent" field.
func UserAgentEqualFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "userAgent" field.
func UserAgentContainsFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldContainsFold(FieldIP, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "userID" field.
func UserIDIsNil() predicate.SignupLink {
	return predicate.SignupLink(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "userID" field.
func UserIDNotNil() predicate.SignupLink {
	return predicate.SignupLink(sql.FieldNotNull(FieldUserID))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SignupLink {
	return predicate.SignupLink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SignupLink {
	return predicate.SignupLink(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SignupLink) predicate.SignupLink {
	return predicate.SignupLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SignupLink) predicate.SignupLink {
	return predicate.SignupLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SignupLink) predicate.SignupLink {
	return predicate.SignupLink(sql.NotPredicates(p))
}
