// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldLockedUntil holds the string denoting the lockeduntil field in the database.
	FieldLockedUntil = "locked_until"
	// FieldDownloadSessionsValidFrom holds the string denoting the downloadsessionsvalidfrom field in the database.
	FieldDownloadSessionsValidFrom = "download_sessions_valid_from"
	// EdgeStash holds the string denoting the stash edge name in mutations.
	EdgeStash = "stash"
	// EdgeMessengers holds the string denoting the messengers edge name in mutations.
	EdgeMessengers = "messengers"
	// EdgeDownloadSessions holds the string denoting the downloadsessions edge name in mutations.
	EdgeDownloadSessions = "downloadSessions"
	// EdgeSignupLink holds the string denoting the signuplink edge name in mutations.
	EdgeSignupLink = "signupLink"
	// EdgeLogs holds the string denoting the logs edge name in mutations.
	EdgeLogs = "logs"
	// Table holds the table name of the user in the database.
	Table = "users"
	// StashTable is the table that holds the stash relation/edge.
	StashTable = "stashes"
	// StashInverseTable is the table name for the Stash entity.
	// It exists in this package in order to avoid circular dependency with the "stash" package.
	StashInverseTable = "stashes"
	// StashColumn is the table column denoting the stash relation/edge.
	StashColumn = "user_id"
	// MessengersTable is the table that holds the messengers relation/edge.
	MessengersTable = "user_messengers"
	// MessengersInverseTable is the table name for the UserMessenger entity.
	// It exists in this package in order to avoid circular dependency with the "usermessenger" package.
	MessengersInverseTable = "user_messengers"
	// MessengersColumn is the table column denoting the messengers relation/edge.
	MessengersColumn = "user_id"
	// DownloadSessionsTable is the table that holds the downloadSessions relation/edge.
	DownloadSessionsTable = "download_sessions"
	// DownloadSessionsInverseTable is the table name for the DownloadSession entity.
	// It exists in this package in order to avoid circular dependency with the "downloadsession" package.
	DownloadSessionsInverseTable = "download_sessions"
	// DownloadSessionsColumn is the table column denoting the downloadSessions relation/edge.
	DownloadSessionsColumn = "user_id"
	// SignupLinkTable is the table that holds the signupLink relation/edge.
	SignupLinkTable = "signup_links"
	// SignupLinkInverseTable is the table name for the SignupLink entity.
	// It exists in this package in order to avoid circular dependency with the "signuplink" package.
	SignupLinkInverseTable = "signup_links"
	// SignupLinkColumn is the table column denoting the signupLink relation/edge.
	SignupLinkColumn = "user_id"
	// LogsTable is the table that holds the logs relation/edge.
	LogsTable = "log_entries"
	// LogsInverseTable is the table name for the LogEntry entity.
	// It exists in this package in order to avoid circular dependency with the "logentry" package.
	LogsInverseTable = "log_entries"
	// LogsColumn is the table column denoting the logs relation/edge.
	LogsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUsername,
	FieldLocked,
	FieldLockedUntil,
	FieldDownloadSessionsValidFrom,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultLocked holds the default value on creation for the "locked" field.
	DefaultLocked bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByLocked orders the results by the locked field.
func ByLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocked, opts...).ToFunc()
}

// ByLockedUntil orders the results by the lockedUntil field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByDownloadSessionsValidFrom orders the results by the downloadSessionsValidFrom field.
func ByDownloadSessionsValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadSessionsValidFrom, opts...).ToFunc()
}

// ByStashField orders the results by stash field.
func ByStashField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStashStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessengersCount orders the results by messengers count.
func ByMessengersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessengersStep(), opts...)
	}
}

// ByMessengers orders the results by messengers terms.
func ByMessengers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessengersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDownloadSessionsCount orders the results by downloadSessions count.
func ByDownloadSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDownloadSessionsStep(), opts...)
	}
}

// ByDownloadSessions orders the results by downloadSessions terms.
func ByDownloadSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySignupLinkField orders the results by signupLink field.
func BySignupLinkField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSignupLinkStep(), sql.OrderByField(field, opts...))
	}
}

// ByLogsCount orders the results by logs count.
func ByLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLogsStep(), opts...)
	}
}

// ByLogs orders the results by logs terms.
func ByLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStashStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StashInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, StashTable, StashColumn),
	)
}
func newMessengersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessengersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessengersTable, MessengersColumn),
	)
}
func newDownloadSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DownloadSessionsTable, DownloadSessionsColumn),
	)
}
func newSignupLinkStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SignupLinkInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, SignupLinkTable, SignupLinkColumn),
	)
}
func newLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
	)
}
