// Code generated by ent, DO NOT EDIT.

package stash

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the stash type in the database.
	Label = "stash"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastDownloadAt holds the string denoting the lastdownloadat field in the database.
	FieldLastDownloadAt = "last_download_at"
	// FieldPublicName holds the string denoting the publicname field in the database.
	FieldPublicName = "public_name"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldFileName holds the string denoting the filename field in the database.
	FieldFileName = "file_name"
	// FieldEncryptionDataKey holds the string denoting the encryptiondatakey field in the database.
	FieldEncryptionDataKey = "encryption_data_key"
	// FieldPasswordSalt holds the string denoting the passwordsalt field in the database.
	FieldPasswordSalt = "password_salt"
	// FieldHashTime holds the string denoting the hashtime field in the database.
	FieldHashTime = "hash_time"
	// FieldHashMemory holds the string denoting the hashmemory field in the database.
	FieldHashMemory = "hash_memory"
	// FieldHashThreads holds the string denoting the hashthreads field in the database.
	FieldHashThreads = "hash_threads"
	// FieldIsSelfLocked holds the string denoting the isselflocked field in the database.
	FieldIsSelfLocked = "is_self_locked"
	// FieldIsAdminLocked holds the string denoting the isadminlocked field in the database.
	FieldIsAdminLocked = "is_admin_locked"
	// FieldSelfLockedUntil holds the string denoting the selflockeduntil field in the database.
	FieldSelfLockedUntil = "self_locked_until"
	// FieldDownloadSessionsValidFrom holds the string denoting the downloadsessionsvalidfrom field in the database.
	FieldDownloadSessionsValidFrom = "download_sessions_valid_from"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDownloadSessions holds the string denoting the downloadsessions edge name in mutations.
	EdgeDownloadSessions = "downloadSessions"
	// Table holds the table name of the stash in the database.
	Table = "stashes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "stashes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// DownloadSessionsTable is the table that holds the downloadSessions relation/edge.
	DownloadSessionsTable = "download_sessions"
	// DownloadSessionsInverseTable is the table name for the DownloadSession entity.
	// It exists in this package in order to avoid circular dependency with the "downloadsession" package.
	DownloadSessionsInverseTable = "download_sessions"
	// DownloadSessionsColumn is the table column denoting the downloadSessions relation/edge.
	DownloadSessionsColumn = "stash_id"
)

// Columns holds all SQL columns for stash fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLastDownloadAt,
	FieldPublicName,
	FieldContent,
	FieldFileName,
	FieldEncryptionDataKey,
	FieldPasswordSalt,
	FieldHashTime,
	FieldHashMemory,
	FieldHashThreads,
	FieldIsSelfLocked,
	FieldIsAdminLocked,
	FieldSelfLockedUntil,
	FieldDownloadSessionsValidFrom,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicNameValidator is a validator for the "publicName" field. It is called by the builders before save.
	PublicNameValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func([]byte) error
	// FileNameValidator is a validator for the "fileName" field. It is called by the builders before save.
	FileNameValidator func([]byte) error
	// EncryptionDataKeyValidator is a validator for the "encryptionDataKey" field. It is called by the builders before save.
	EncryptionDataKeyValidator func([]byte) error
	// PasswordSaltValidator is a validator for the "passwordSalt" field. It is called by the builders before save.
	PasswordSaltValidator func([]byte) error
	// DefaultIsSelfLocked holds the default value on creation for the "isSelfLocked" field.
	DefaultIsSelfLocked bool
	// DefaultIsAdminLocked holds the default value on creation for the "isAdminLocked" field.
	DefaultIsAdminLocked bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Stash queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastDownloadAt orders the results by the lastDownloadAt field.
func ByLastDownloadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDownloadAt, opts...).ToFunc()
}

// ByPublicName orders the results by the publicName field.
func ByPublicName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicName, opts...).ToFunc()
}

// ByHashTime orders the results by the hashTime field.
func ByHashTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashTime, opts...).ToFunc()
}

// ByHashMemory orders the results by the hashMemory field.
func ByHashMemory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashMemory, opts...).ToFunc()
}

// ByHashThreads orders the results by the hashThreads field.
func ByHashThreads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashThreads, opts...).ToFunc()
}

// ByIsSelfLocked orders the results by the isSelfLocked field.
func ByIsSelfLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSelfLocked, opts...).ToFunc()
}

// ByIsAdminLocked orders the results by the isAdminLocked field.
func ByIsAdminLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdminLocked, opts...).ToFunc()
}

// BySelfLockedUntil orders the results by the selfLockedUntil field.
func BySelfLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelfLockedUntil, opts...).ToFunc()
}

// ByDownloadSessionsValidFrom orders the results by the downloadSessionsValidFrom field.
func ByDownloadSessionsValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadSessionsValidFrom, opts...).ToFunc()
}

// ByUserID orders the results by the userID field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDownloadSessionsCount orders the results by downloadSessions count.
func ByDownloadSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDownloadSessionsStep(), opts...)
	}
}

// ByDownloadSessions orders the results by downloadSessions terms.
func ByDownloadSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newDownloadSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DownloadSessionsTable, DownloadSessionsColumn),
	)
}
