// Code generated by ent, DO NOT EDIT.

package stash

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastDownloadAt applies equality check predicate on the "lastDownloadAt" field. It's identical to LastDownloadAtEQ.
func LastDownloadAt(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldLastDownloadAt, v))
}

// PublicName applies equality check predicate on the "publicName" field. It's identical to PublicNameEQ.
func PublicName(v string) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldPublicName, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldContent, v))
}

// FileName applies equality check predicate on the "fileName" field. It's identical to FileNameEQ.
func FileName(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldFileName, v))
}

// EncryptionDataKey applies equality check predicate on the "encryptionDataKey" field. It's identical to EncryptionDataKeyEQ.
func EncryptionDataKey(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldEncryptionDataKey, v))
}

// PasswordSalt applies equality check predicate on the "passwordSalt" field. It's identical to PasswordSaltEQ.
func PasswordSalt(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldPasswordSalt, v))
}

// HashTime applies equality check predicate on the "hashTime" field. It's identical to HashTimeEQ.
func HashTime(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashTime, v))
}

// HashMemory applies equality check predicate on the "hashMemory" field. It's identical to HashMemoryEQ.
func HashMemory(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashMemory, v))
}

// HashThreads applies equality check predicate on the "hashThreads" field. It's identical to HashThreadsEQ.
func HashThreads(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashThreads, v))
}

// SelfLocked applies equality check predicate on the "selfLocked" field. It's identical to SelfLockedEQ.
func SelfLocked(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldSelfLocked, v))
}

// AdminLocked applies equality check predicate on the "adminLocked" field. It's identical to AdminLockedEQ.
func AdminLocked(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldAdminLocked, v))
}

// SelfLockedUntil applies equality check predicate on the "selfLockedUntil" field. It's identical to SelfLockedUntilEQ.
func SelfLockedUntil(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldSelfLockedUntil, v))
}

// DownloadSessionsValidFrom applies equality check predicate on the "downloadSessionsValidFrom" field. It's identical to DownloadSessionsValidFromEQ.
func DownloadSessionsValidFrom(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldDownloadSessionsValidFrom, v))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastDownloadAtEQ applies the EQ predicate on the "lastDownloadAt" field.
func LastDownloadAtEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldLastDownloadAt, v))
}

// LastDownloadAtNEQ applies the NEQ predicate on the "lastDownloadAt" field.
func LastDownloadAtNEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldLastDownloadAt, v))
}

// LastDownloadAtIn applies the In predicate on the "lastDownloadAt" field.
func LastDownloadAtIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldLastDownloadAt, vs...))
}

// LastDownloadAtNotIn applies the NotIn predicate on the "lastDownloadAt" field.
func LastDownloadAtNotIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldLastDownloadAt, vs...))
}

// LastDownloadAtGT applies the GT predicate on the "lastDownloadAt" field.
func LastDownloadAtGT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldLastDownloadAt, v))
}

// LastDownloadAtGTE applies the GTE predicate on the "lastDownloadAt" field.
func LastDownloadAtGTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldLastDownloadAt, v))
}

// LastDownloadAtLT applies the LT predicate on the "lastDownloadAt" field.
func LastDownloadAtLT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldLastDownloadAt, v))
}

// LastDownloadAtLTE applies the LTE predicate on the "lastDownloadAt" field.
func LastDownloadAtLTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldLastDownloadAt, v))
}

// LastDownloadAtIsNil applies the IsNil predicate on the "lastDownloadAt" field.
func LastDownloadAtIsNil() predicate.Stash {
	return predicate.Stash(sql.FieldIsNull(FieldLastDownloadAt))
}

// LastDownloadAtNotNil applies the NotNil predicate on the "lastDownloadAt" field.
func LastDownloadAtNotNil() predicate.Stash {
	return predicate.Stash(sql.FieldNotNull(FieldLastDownloadAt))
}

// PublicNameEQ applies the EQ predicate on the "publicName" field.
func PublicNameEQ(v string) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldPublicName, v))
}

// PublicNameNEQ applies the NEQ predicate on the "publicName" field.
func PublicNameNEQ(v string) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldPublicName, v))
}

// PublicNameIn applies the In predicate on the "publicName" field.
func PublicNameIn(vs ...string) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldPublicName, vs...))
}

// PublicNameNotIn applies the NotIn predicate on the "publicName" field.
func PublicNameNotIn(vs ...string) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldPublicName, vs...))
}

// PublicNameGT applies the GT predicate on the "publicName" field.
func PublicNameGT(v string) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldPublicName, v))
}

// PublicNameGTE applies the GTE predicate on the "publicName" field.
func PublicNameGTE(v string) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldPublicName, v))
}

// PublicNameLT applies the LT predicate on the "publicName" field.
func PublicNameLT(v string) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldPublicName, v))
}

// PublicNameLTE applies the LTE predicate on the "publicName" field.
func PublicNameLTE(v string) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldPublicName, v))
}

// PublicNameContains applies the Contains predicate on the "publicName" field.
func PublicNameContains(v string) predicate.Stash {
	return predicate.Stash(sql.FieldContains(FieldPublicName, v))
}

// PublicNameHasPrefix applies the HasPrefix predicate on the "publicName" field.
func PublicNameHasPrefix(v string) predicate.Stash {
	return predicate.Stash(sql.FieldHasPrefix(FieldPublicName, v))
}

// PublicNameHasSuffix applies the HasSuffix predicate on the "publicName" field.
func PublicNameHasSuffix(v string) predicate.Stash {
	return predicate.Stash(sql.FieldHasSuffix(FieldPublicName, v))
}

// PublicNameEqualFold applies the EqualFold predicate on the "publicName" field.
func PublicNameEqualFold(v string) predicate.Stash {
	return predicate.Stash(sql.FieldEqualFold(FieldPublicName, v))
}

// PublicNameContainsFold applies the ContainsFold predicate on the "publicName" field.
func PublicNameContainsFold(v string) predicate.Stash {
	return predicate.Stash(sql.FieldContainsFold(FieldPublicName, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldContent, v))
}

// FileNameEQ applies the EQ predicate on the "fileName" field.
func FileNameEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "fileName" field.
func FileNameNEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "fileName" field.
func FileNameIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "fileName" field.
func FileNameNotIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "fileName" field.
func FileNameGT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "fileName" field.
func FileNameGTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "fileName" field.
func FileNameLT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "fileName" field.
func FileNameLTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldFileName, v))
}

// EncryptionDataKeyEQ applies the EQ predicate on the "encryptionDataKey" field.
func EncryptionDataKeyEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldEncryptionDataKey, v))
}

// EncryptionDataKeyNEQ applies the NEQ predicate on the "encryptionDataKey" field.
func EncryptionDataKeyNEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldEncryptionDataKey, v))
}

// EncryptionDataKeyIn applies the In predicate on the "encryptionDataKey" field.
func EncryptionDataKeyIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldEncryptionDataKey, vs...))
}

// EncryptionDataKeyNotIn applies the NotIn predicate on the "encryptionDataKey" field.
func EncryptionDataKeyNotIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldEncryptionDataKey, vs...))
}

// EncryptionDataKeyGT applies the GT predicate on the "encryptionDataKey" field.
func EncryptionDataKeyGT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldEncryptionDataKey, v))
}

// EncryptionDataKeyGTE applies the GTE predicate on the "encryptionDataKey" field.
func EncryptionDataKeyGTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldEncryptionDataKey, v))
}

// EncryptionDataKeyLT applies the LT predicate on the "encryptionDataKey" field.
func EncryptionDataKeyLT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldEncryptionDataKey, v))
}

// EncryptionDataKeyLTE applies the LTE predicate on the "encryptionDataKey" field.
func EncryptionDataKeyLTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldEncryptionDataKey, v))
}

// PasswordSaltEQ applies the EQ predicate on the "passwordSalt" field.
func PasswordSaltEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldPasswordSalt, v))
}

// PasswordSaltNEQ applies the NEQ predicate on the "passwordSalt" field.
func PasswordSaltNEQ(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldPasswordSalt, v))
}

// PasswordSaltIn applies the In predicate on the "passwordSalt" field.
func PasswordSaltIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldPasswordSalt, vs...))
}

// PasswordSaltNotIn applies the NotIn predicate on the "passwordSalt" field.
func PasswordSaltNotIn(vs ...[]byte) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldPasswordSalt, vs...))
}

// PasswordSaltGT applies the GT predicate on the "passwordSalt" field.
func PasswordSaltGT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldPasswordSalt, v))
}

// PasswordSaltGTE applies the GTE predicate on the "passwordSalt" field.
func PasswordSaltGTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldPasswordSalt, v))
}

// PasswordSaltLT applies the LT predicate on the "passwordSalt" field.
func PasswordSaltLT(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldPasswordSalt, v))
}

// PasswordSaltLTE applies the LTE predicate on the "passwordSalt" field.
func PasswordSaltLTE(v []byte) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldPasswordSalt, v))
}

// HashTimeEQ applies the EQ predicate on the "hashTime" field.
func HashTimeEQ(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashTime, v))
}

// HashTimeNEQ applies the NEQ predicate on the "hashTime" field.
func HashTimeNEQ(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldHashTime, v))
}

// HashTimeIn applies the In predicate on the "hashTime" field.
func HashTimeIn(vs ...uint32) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldHashTime, vs...))
}

// HashTimeNotIn applies the NotIn predicate on the "hashTime" field.
func HashTimeNotIn(vs ...uint32) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldHashTime, vs...))
}

// HashTimeGT applies the GT predicate on the "hashTime" field.
func HashTimeGT(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldHashTime, v))
}

// HashTimeGTE applies the GTE predicate on the "hashTime" field.
func HashTimeGTE(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldHashTime, v))
}

// HashTimeLT applies the LT predicate on the "hashTime" field.
func HashTimeLT(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldHashTime, v))
}

// HashTimeLTE applies the LTE predicate on the "hashTime" field.
func HashTimeLTE(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldHashTime, v))
}

// HashMemoryEQ applies the EQ predicate on the "hashMemory" field.
func HashMemoryEQ(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashMemory, v))
}

// HashMemoryNEQ applies the NEQ predicate on the "hashMemory" field.
func HashMemoryNEQ(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldHashMemory, v))
}

// HashMemoryIn applies the In predicate on the "hashMemory" field.
func HashMemoryIn(vs ...uint32) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldHashMemory, vs...))
}

// HashMemoryNotIn applies the NotIn predicate on the "hashMemory" field.
func HashMemoryNotIn(vs ...uint32) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldHashMemory, vs...))
}

// HashMemoryGT applies the GT predicate on the "hashMemory" field.
func HashMemoryGT(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldHashMemory, v))
}

// HashMemoryGTE applies the GTE predicate on the "hashMemory" field.
func HashMemoryGTE(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldHashMemory, v))
}

// HashMemoryLT applies the LT predicate on the "hashMemory" field.
func HashMemoryLT(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldHashMemory, v))
}

// HashMemoryLTE applies the LTE predicate on the "hashMemory" field.
func HashMemoryLTE(v uint32) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldHashMemory, v))
}

// HashThreadsEQ applies the EQ predicate on the "hashThreads" field.
func HashThreadsEQ(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldHashThreads, v))
}

// HashThreadsNEQ applies the NEQ predicate on the "hashThreads" field.
func HashThreadsNEQ(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldHashThreads, v))
}

// HashThreadsIn applies the In predicate on the "hashThreads" field.
func HashThreadsIn(vs ...uint8) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldHashThreads, vs...))
}

// HashThreadsNotIn applies the NotIn predicate on the "hashThreads" field.
func HashThreadsNotIn(vs ...uint8) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldHashThreads, vs...))
}

// HashThreadsGT applies the GT predicate on the "hashThreads" field.
func HashThreadsGT(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldHashThreads, v))
}

// HashThreadsGTE applies the GTE predicate on the "hashThreads" field.
func HashThreadsGTE(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldHashThreads, v))
}

// HashThreadsLT applies the LT predicate on the "hashThreads" field.
func HashThreadsLT(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldHashThreads, v))
}

// HashThreadsLTE applies the LTE predicate on the "hashThreads" field.
func HashThreadsLTE(v uint8) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldHashThreads, v))
}

// SelfLockedEQ applies the EQ predicate on the "selfLocked" field.
func SelfLockedEQ(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldSelfLocked, v))
}

// SelfLockedNEQ applies the NEQ predicate on the "selfLocked" field.
func SelfLockedNEQ(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldSelfLocked, v))
}

// AdminLockedEQ applies the EQ predicate on the "adminLocked" field.
func AdminLockedEQ(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldAdminLocked, v))
}

// AdminLockedNEQ applies the NEQ predicate on the "adminLocked" field.
func AdminLockedNEQ(v bool) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldAdminLocked, v))
}

// SelfLockedUntilEQ applies the EQ predicate on the "selfLockedUntil" field.
func SelfLockedUntilEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldSelfLockedUntil, v))
}

// SelfLockedUntilNEQ applies the NEQ predicate on the "selfLockedUntil" field.
func SelfLockedUntilNEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldSelfLockedUntil, v))
}

// SelfLockedUntilIn applies the In predicate on the "selfLockedUntil" field.
func SelfLockedUntilIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldSelfLockedUntil, vs...))
}

// SelfLockedUntilNotIn applies the NotIn predicate on the "selfLockedUntil" field.
func SelfLockedUntilNotIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldSelfLockedUntil, vs...))
}

// SelfLockedUntilGT applies the GT predicate on the "selfLockedUntil" field.
func SelfLockedUntilGT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldSelfLockedUntil, v))
}

// SelfLockedUntilGTE applies the GTE predicate on the "selfLockedUntil" field.
func SelfLockedUntilGTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldSelfLockedUntil, v))
}

// SelfLockedUntilLT applies the LT predicate on the "selfLockedUntil" field.
func SelfLockedUntilLT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldSelfLockedUntil, v))
}

// SelfLockedUntilLTE applies the LTE predicate on the "selfLockedUntil" field.
func SelfLockedUntilLTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldSelfLockedUntil, v))
}

// SelfLockedUntilIsNil applies the IsNil predicate on the "selfLockedUntil" field.
func SelfLockedUntilIsNil() predicate.Stash {
	return predicate.Stash(sql.FieldIsNull(FieldSelfLockedUntil))
}

// SelfLockedUntilNotNil applies the NotNil predicate on the "selfLockedUntil" field.
func SelfLockedUntilNotNil() predicate.Stash {
	return predicate.Stash(sql.FieldNotNull(FieldSelfLockedUntil))
}

// DownloadSessionsValidFromEQ applies the EQ predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldDownloadSessionsValidFrom, v))
}

// DownloadSessionsValidFromNEQ applies the NEQ predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromNEQ(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldDownloadSessionsValidFrom, v))
}

// DownloadSessionsValidFromIn applies the In predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldDownloadSessionsValidFrom, vs...))
}

// DownloadSessionsValidFromNotIn applies the NotIn predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromNotIn(vs ...time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldDownloadSessionsValidFrom, vs...))
}

// DownloadSessionsValidFromGT applies the GT predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromGT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGT(FieldDownloadSessionsValidFrom, v))
}

// DownloadSessionsValidFromGTE applies the GTE predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromGTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldGTE(FieldDownloadSessionsValidFrom, v))
}

// DownloadSessionsValidFromLT applies the LT predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromLT(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLT(FieldDownloadSessionsValidFrom, v))
}

// DownloadSessionsValidFromLTE applies the LTE predicate on the "downloadSessionsValidFrom" field.
func DownloadSessionsValidFromLTE(v time.Time) predicate.Stash {
	return predicate.Stash(sql.FieldLTE(FieldDownloadSessionsValidFrom, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Stash {
	return predicate.Stash(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Stash {
	return predicate.Stash(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Stash {
	return predicate.Stash(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDownloadSessions applies the HasEdge predicate on the "downloadSessions" edge.
func HasDownloadSessions() predicate.Stash {
	return predicate.Stash(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DownloadSessionsTable, DownloadSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDownloadSessionsWith applies the HasEdge predicate on the "downloadSessions" edge with a given conditions (other predicates).
func HasDownloadSessionsWith(preds ...predicate.DownloadSession) predicate.Stash {
	return predicate.Stash(func(s *sql.Selector) {
		step := newDownloadSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stash) predicate.Stash {
	return predicate.Stash(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stash) predicate.Stash {
	return predicate.Stash(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stash) predicate.Stash {
	return predicate.Stash(sql.NotPredicates(p))
}
