// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/downloadsession"
	"github.com/NicoClack/cryptic-stash/backend/ent/loginalert"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// DownloadSessionUpdate is the builder for updating DownloadSession entities.
type DownloadSessionUpdate struct {
	config
	hooks    []Hook
	mutation *DownloadSessionMutation
}

// Where appends a list predicates to the DownloadSessionUpdate builder.
func (_u *DownloadSessionUpdate) Where(ps ...predicate.DownloadSession) *DownloadSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *DownloadSessionUpdate) SetCreatedAt(v time.Time) *DownloadSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableCreatedAt(v *time.Time) *DownloadSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DownloadSessionUpdate) SetUpdatedAt(v time.Time) *DownloadSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHashedAuthCode sets the "hashedAuthCode" field.
func (_u *DownloadSessionUpdate) SetHashedAuthCode(v []byte) *DownloadSessionUpdate {
	_u.mutation.SetHashedAuthCode(v)
	return _u
}

// SetValidFrom sets the "validFrom" field.
func (_u *DownloadSessionUpdate) SetValidFrom(v time.Time) *DownloadSessionUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "validFrom" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableValidFrom(v *time.Time) *DownloadSessionUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidUntil sets the "validUntil" field.
func (_u *DownloadSessionUpdate) SetValidUntil(v time.Time) *DownloadSessionUpdate {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "validUntil" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableValidUntil(v *time.Time) *DownloadSessionUpdate {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *DownloadSessionUpdate) SetUserAgent(v string) *DownloadSessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableUserAgent(v *string) *DownloadSessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *DownloadSessionUpdate) SetIP(v string) *DownloadSessionUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableIP(v *string) *DownloadSessionUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *DownloadSessionUpdate) SetUserID(v uuid.UUID) *DownloadSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *DownloadSessionUpdate) SetNillableUserID(v *uuid.UUID) *DownloadSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DownloadSessionUpdate) SetUser(v *User) *DownloadSessionUpdate {
	return _u.SetUserID(v.ID)
}

// AddLoginAlertIDs adds the "loginAlerts" edge to the LoginAlert entity by IDs.
func (_u *DownloadSessionUpdate) AddLoginAlertIDs(ids ...uuid.UUID) *DownloadSessionUpdate {
	_u.mutation.AddLoginAlertIDs(ids...)
	return _u
}

// AddLoginAlerts adds the "loginAlerts" edges to the LoginAlert entity.
func (_u *DownloadSessionUpdate) AddLoginAlerts(v ...*LoginAlert) *DownloadSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoginAlertIDs(ids...)
}

// Mutation returns the DownloadSessionMutation object of the builder.
func (_u *DownloadSessionUpdate) Mutation() *DownloadSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DownloadSessionUpdate) ClearUser() *DownloadSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearLoginAlerts clears all "loginAlerts" edges to the LoginAlert entity.
func (_u *DownloadSessionUpdate) ClearLoginAlerts() *DownloadSessionUpdate {
	_u.mutation.ClearLoginAlerts()
	return _u
}

// RemoveLoginAlertIDs removes the "loginAlerts" edge to LoginAlert entities by IDs.
func (_u *DownloadSessionUpdate) RemoveLoginAlertIDs(ids ...uuid.UUID) *DownloadSessionUpdate {
	_u.mutation.RemoveLoginAlertIDs(ids...)
	return _u
}

// RemoveLoginAlerts removes "loginAlerts" edges to LoginAlert entities.
func (_u *DownloadSessionUpdate) RemoveLoginAlerts(v ...*LoginAlert) *DownloadSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoginAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DownloadSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownloadSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DownloadSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownloadSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DownloadSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := downloadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownloadSessionUpdate) check() error {
	if v, ok := _u.mutation.HashedAuthCode(); ok {
		if err := downloadsession.HashedAuthCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedAuthCode", err: fmt.Errorf(`ent: validator failed for field "DownloadSession.hashedAuthCode": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DownloadSession.user"`)
	}
	return nil
}

func (_u *DownloadSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downloadsession.Table, downloadsession.Columns, sqlgraph.NewFieldSpec(downloadsession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(downloadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(downloadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HashedAuthCode(); ok {
		_spec.SetField(downloadsession.FieldHashedAuthCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(downloadsession.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(downloadsession.FieldValidUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(downloadsession.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(downloadsession.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadsession.UserTable,
			Columns: []string{downloadsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadsession.UserTable,
			Columns: []string{downloadsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LoginAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoginAlertsIDs(); len(nodes) > 0 && !_u.mutation.LoginAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoginAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downloadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DownloadSessionUpdateOne is the builder for updating a single DownloadSession entity.
type DownloadSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DownloadSessionMutation
}

// SetCreatedAt sets the "createdAt" field.
func (_u *DownloadSessionUpdateOne) SetCreatedAt(v time.Time) *DownloadSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DownloadSessionUpdateOne) SetUpdatedAt(v time.Time) *DownloadSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHashedAuthCode sets the "hashedAuthCode" field.
func (_u *DownloadSessionUpdateOne) SetHashedAuthCode(v []byte) *DownloadSessionUpdateOne {
	_u.mutation.SetHashedAuthCode(v)
	return _u
}

// SetValidFrom sets the "validFrom" field.
func (_u *DownloadSessionUpdateOne) SetValidFrom(v time.Time) *DownloadSessionUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "validFrom" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableValidFrom(v *time.Time) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidUntil sets the "validUntil" field.
func (_u *DownloadSessionUpdateOne) SetValidUntil(v time.Time) *DownloadSessionUpdateOne {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "validUntil" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableValidUntil(v *time.Time) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *DownloadSessionUpdateOne) SetUserAgent(v string) *DownloadSessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableUserAgent(v *string) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *DownloadSessionUpdateOne) SetIP(v string) *DownloadSessionUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableIP(v *string) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *DownloadSessionUpdateOne) SetUserID(v uuid.UUID) *DownloadSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *DownloadSessionUpdateOne) SetNillableUserID(v *uuid.UUID) *DownloadSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DownloadSessionUpdateOne) SetUser(v *User) *DownloadSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddLoginAlertIDs adds the "loginAlerts" edge to the LoginAlert entity by IDs.
func (_u *DownloadSessionUpdateOne) AddLoginAlertIDs(ids ...uuid.UUID) *DownloadSessionUpdateOne {
	_u.mutation.AddLoginAlertIDs(ids...)
	return _u
}

// AddLoginAlerts adds the "loginAlerts" edges to the LoginAlert entity.
func (_u *DownloadSessionUpdateOne) AddLoginAlerts(v ...*LoginAlert) *DownloadSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLoginAlertIDs(ids...)
}

// Mutation returns the DownloadSessionMutation object of the builder.
func (_u *DownloadSessionUpdateOne) Mutation() *DownloadSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DownloadSessionUpdateOne) ClearUser() *DownloadSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearLoginAlerts clears all "loginAlerts" edges to the LoginAlert entity.
func (_u *DownloadSessionUpdateOne) ClearLoginAlerts() *DownloadSessionUpdateOne {
	_u.mutation.ClearLoginAlerts()
	return _u
}

// RemoveLoginAlertIDs removes the "loginAlerts" edge to LoginAlert entities by IDs.
func (_u *DownloadSessionUpdateOne) RemoveLoginAlertIDs(ids ...uuid.UUID) *DownloadSessionUpdateOne {
	_u.mutation.RemoveLoginAlertIDs(ids...)
	return _u
}

// RemoveLoginAlerts removes "loginAlerts" edges to LoginAlert entities.
func (_u *DownloadSessionUpdateOne) RemoveLoginAlerts(v ...*LoginAlert) *DownloadSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLoginAlertIDs(ids...)
}

// Where appends a list predicates to the DownloadSessionUpdate builder.
func (_u *DownloadSessionUpdateOne) Where(ps ...predicate.DownloadSession) *DownloadSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DownloadSessionUpdateOne) Select(field string, fields ...string) *DownloadSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DownloadSession entity.
func (_u *DownloadSessionUpdateOne) Save(ctx context.Context) (*DownloadSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DownloadSessionUpdateOne) SaveX(ctx context.Context) *DownloadSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DownloadSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DownloadSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DownloadSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := downloadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DownloadSessionUpdateOne) check() error {
	if v, ok := _u.mutation.HashedAuthCode(); ok {
		if err := downloadsession.HashedAuthCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedAuthCode", err: fmt.Errorf(`ent: validator failed for field "DownloadSession.hashedAuthCode": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DownloadSession.user"`)
	}
	return nil
}

func (_u *DownloadSessionUpdateOne) sqlSave(ctx context.Context) (_node *DownloadSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(downloadsession.Table, downloadsession.Columns, sqlgraph.NewFieldSpec(downloadsession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DownloadSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, downloadsession.FieldID)
		for _, f := range fields {
			if !downloadsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != downloadsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(downloadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(downloadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HashedAuthCode(); ok {
		_spec.SetField(downloadsession.FieldHashedAuthCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(downloadsession.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(downloadsession.FieldValidUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(downloadsession.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(downloadsession.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadsession.UserTable,
			Columns: []string{downloadsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   downloadsession.UserTable,
			Columns: []string{downloadsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LoginAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLoginAlertsIDs(); len(nodes) > 0 && !_u.mutation.LoginAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LoginAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   downloadsession.LoginAlertsTable,
			Columns: []string{downloadsession.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DownloadSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{downloadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
