// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NicoClack/cryptic-stash/backend/ent/downloadsession"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// DownloadSession is the model entity for the DownloadSession schema.
type DownloadSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// HashedAuthCode holds the value of the "hashedAuthCode" field.
	HashedAuthCode []byte `json:"hashedAuthCode,omitempty"`
	// ValidFrom holds the value of the "validFrom" field.
	ValidFrom time.Time `json:"validFrom,omitempty"`
	// ValidUntil holds the value of the "validUntil" field.
	ValidUntil time.Time `json:"validUntil,omitempty"`
	// UserAgent holds the value of the "userAgent" field.
	UserAgent string `json:"userAgent,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// UserID holds the value of the "userID" field.
	UserID uuid.UUID `json:"userID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DownloadSessionQuery when eager-loading is set.
	Edges        DownloadSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DownloadSessionEdges holds the relations/edges for other nodes in the graph.
type DownloadSessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// LoginAlerts holds the value of the loginAlerts edge.
	LoginAlerts []*LoginAlert `json:"loginAlerts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DownloadSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// LoginAlertsOrErr returns the LoginAlerts value or an error if the edge
// was not loaded in eager-loading.
func (e DownloadSessionEdges) LoginAlertsOrErr() ([]*LoginAlert, error) {
	if e.loadedTypes[1] {
		return e.LoginAlerts, nil
	}
	return nil, &NotLoadedError{edge: "loginAlerts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DownloadSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case downloadsession.FieldHashedAuthCode:
			values[i] = new([]byte)
		case downloadsession.FieldUserAgent, downloadsession.FieldIP:
			values[i] = new(sql.NullString)
		case downloadsession.FieldCreatedAt, downloadsession.FieldValidFrom, downloadsession.FieldValidUntil:
			values[i] = new(sql.NullTime)
		case downloadsession.FieldID, downloadsession.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DownloadSession fields.
func (_m *DownloadSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case downloadsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case downloadsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case downloadsession.FieldHashedAuthCode:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hashedAuthCode", values[i])
			} else if value != nil {
				_m.HashedAuthCode = *value
			}
		case downloadsession.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field validFrom", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case downloadsession.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field validUntil", values[i])
			} else if value.Valid {
				_m.ValidUntil = value.Time
			}
		case downloadsession.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userAgent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case downloadsession.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case downloadsession.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field userID", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DownloadSession.
// This includes values selected through modifiers, order, etc.
func (_m *DownloadSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DownloadSession entity.
func (_m *DownloadSession) QueryUser() *UserQuery {
	return NewDownloadSessionClient(_m.config).QueryUser(_m)
}

// QueryLoginAlerts queries the "loginAlerts" edge of the DownloadSession entity.
func (_m *DownloadSession) QueryLoginAlerts() *LoginAlertQuery {
	return NewDownloadSessionClient(_m.config).QueryLoginAlerts(_m)
}

// Update returns a builder for updating this DownloadSession.
// Note that you need to call DownloadSession.Unwrap() before calling this method if this DownloadSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DownloadSession) Update() *DownloadSessionUpdateOne {
	return NewDownloadSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DownloadSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DownloadSession) Unwrap() *DownloadSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DownloadSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DownloadSession) String() string {
	var builder strings.Builder
	builder.WriteString("DownloadSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("hashedAuthCode=")
	builder.WriteString(fmt.Sprintf("%v", _m.HashedAuthCode))
	builder.WriteString(", ")
	builder.WriteString("validFrom=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("validUntil=")
	builder.WriteString(_m.ValidUntil.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("userAgent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("userID=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// DownloadSessions is a parsable slice of DownloadSession.
type DownloadSessions []*DownloadSession
