// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/invite"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// InviteUpdate is the builder for updating Invite entities.
type InviteUpdate struct {
	config
	hooks    []Hook
	mutation *InviteMutation
}

// Where appends a list predicates to the InviteUpdate builder.
func (_u *InviteUpdate) Where(ps ...predicate.Invite) *InviteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *InviteUpdate) SetCreatedAt(v time.Time) *InviteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableCreatedAt(v *time.Time) *InviteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *InviteUpdate) SetUpdatedAt(v time.Time) *InviteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *InviteUpdate) SetEmail(v string) *InviteUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableEmail(v *string) *InviteUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetHashedCode sets the "hashedCode" field.
func (_u *InviteUpdate) SetHashedCode(v []byte) *InviteUpdate {
	_u.mutation.SetHashedCode(v)
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *InviteUpdate) SetExpiresAt(v time.Time) *InviteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableExpiresAt(v *time.Time) *InviteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetExpiredReason sets the "expiredReason" field.
func (_u *InviteUpdate) SetExpiredReason(v invite.ExpiredReason) *InviteUpdate {
	_u.mutation.SetExpiredReason(v)
	return _u
}

// SetNillableExpiredReason sets the "expiredReason" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableExpiredReason(v *invite.ExpiredReason) *InviteUpdate {
	if v != nil {
		_u.SetExpiredReason(*v)
	}
	return _u
}

// ClearExpiredReason clears the value of the "expiredReason" field.
func (_u *InviteUpdate) ClearExpiredReason() *InviteUpdate {
	_u.mutation.ClearExpiredReason()
	return _u
}

// SetWebauthnChallenge sets the "webauthnChallenge" field.
func (_u *InviteUpdate) SetWebauthnChallenge(v []byte) *InviteUpdate {
	_u.mutation.SetWebauthnChallenge(v)
	return _u
}

// ClearWebauthnChallenge clears the value of the "webauthnChallenge" field.
func (_u *InviteUpdate) ClearWebauthnChallenge() *InviteUpdate {
	_u.mutation.ClearWebauthnChallenge()
	return _u
}

// SetChallengeExpiresAt sets the "challengeExpiresAt" field.
func (_u *InviteUpdate) SetChallengeExpiresAt(v time.Time) *InviteUpdate {
	_u.mutation.SetChallengeExpiresAt(v)
	return _u
}

// SetNillableChallengeExpiresAt sets the "challengeExpiresAt" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableChallengeExpiresAt(v *time.Time) *InviteUpdate {
	if v != nil {
		_u.SetChallengeExpiresAt(*v)
	}
	return _u
}

// ClearChallengeExpiresAt clears the value of the "challengeExpiresAt" field.
func (_u *InviteUpdate) ClearChallengeExpiresAt() *InviteUpdate {
	_u.mutation.ClearChallengeExpiresAt()
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *InviteUpdate) SetUserAgent(v string) *InviteUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableUserAgent(v *string) *InviteUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *InviteUpdate) SetIP(v string) *InviteUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableIP(v *string) *InviteUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *InviteUpdate) SetUserID(v uuid.UUID) *InviteUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *InviteUpdate) SetNillableUserID(v *uuid.UUID) *InviteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "userID" field.
func (_u *InviteUpdate) ClearUserID() *InviteUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InviteUpdate) SetUser(v *User) *InviteUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_u *InviteUpdate) Mutation() *InviteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InviteUpdate) ClearUser() *InviteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedCode(); ok {
		if err := invite.HashedCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedCode", err: fmt.Errorf(`ent: validator failed for field "Invite.hashedCode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpiredReason(); ok {
		if err := invite.ExpiredReasonValidator(v); err != nil {
			return &ValidationError{Name: "expiredReason", err: fmt.Errorf(`ent: validator failed for field "Invite.expiredReason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebauthnChallenge(); ok {
		if err := invite.WebauthnChallengeValidator(v); err != nil {
			return &ValidationError{Name: "webauthnChallenge", err: fmt.Errorf(`ent: validator failed for field "Invite.webauthnChallenge": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invite.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedCode(); ok {
		_spec.SetField(invite.FieldHashedCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredReason(); ok {
		_spec.SetField(invite.FieldExpiredReason, field.TypeEnum, value)
	}
	if _u.mutation.ExpiredReasonCleared() {
		_spec.ClearField(invite.FieldExpiredReason, field.TypeEnum)
	}
	if value, ok := _u.mutation.WebauthnChallenge(); ok {
		_spec.SetField(invite.FieldWebauthnChallenge, field.TypeBytes, value)
	}
	if _u.mutation.WebauthnChallengeCleared() {
		_spec.ClearField(invite.FieldWebauthnChallenge, field.TypeBytes)
	}
	if value, ok := _u.mutation.ChallengeExpiresAt(); ok {
		_spec.SetField(invite.FieldChallengeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ChallengeExpiresAtCleared() {
		_spec.ClearField(invite.FieldChallengeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(invite.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(invite.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invite.UserTable,
			Columns: []string{invite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invite.UserTable,
			Columns: []string{invite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteUpdateOne is the builder for updating a single Invite entity.
type InviteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteMutation
}

// SetCreatedAt sets the "createdAt" field.
func (_u *InviteUpdateOne) SetCreatedAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableCreatedAt(v *time.Time) *InviteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *InviteUpdateOne) SetUpdatedAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *InviteUpdateOne) SetEmail(v string) *InviteUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableEmail(v *string) *InviteUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetHashedCode sets the "hashedCode" field.
func (_u *InviteUpdateOne) SetHashedCode(v []byte) *InviteUpdateOne {
	_u.mutation.SetHashedCode(v)
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *InviteUpdateOne) SetExpiresAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableExpiresAt(v *time.Time) *InviteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetExpiredReason sets the "expiredReason" field.
func (_u *InviteUpdateOne) SetExpiredReason(v invite.ExpiredReason) *InviteUpdateOne {
	_u.mutation.SetExpiredReason(v)
	return _u
}

// SetNillableExpiredReason sets the "expiredReason" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableExpiredReason(v *invite.ExpiredReason) *InviteUpdateOne {
	if v != nil {
		_u.SetExpiredReason(*v)
	}
	return _u
}

// ClearExpiredReason clears the value of the "expiredReason" field.
func (_u *InviteUpdateOne) ClearExpiredReason() *InviteUpdateOne {
	_u.mutation.ClearExpiredReason()
	return _u
}

// SetWebauthnChallenge sets the "webauthnChallenge" field.
func (_u *InviteUpdateOne) SetWebauthnChallenge(v []byte) *InviteUpdateOne {
	_u.mutation.SetWebauthnChallenge(v)
	return _u
}

// ClearWebauthnChallenge clears the value of the "webauthnChallenge" field.
func (_u *InviteUpdateOne) ClearWebauthnChallenge() *InviteUpdateOne {
	_u.mutation.ClearWebauthnChallenge()
	return _u
}

// SetChallengeExpiresAt sets the "challengeExpiresAt" field.
func (_u *InviteUpdateOne) SetChallengeExpiresAt(v time.Time) *InviteUpdateOne {
	_u.mutation.SetChallengeExpiresAt(v)
	return _u
}

// SetNillableChallengeExpiresAt sets the "challengeExpiresAt" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableChallengeExpiresAt(v *time.Time) *InviteUpdateOne {
	if v != nil {
		_u.SetChallengeExpiresAt(*v)
	}
	return _u
}

// ClearChallengeExpiresAt clears the value of the "challengeExpiresAt" field.
func (_u *InviteUpdateOne) ClearChallengeExpiresAt() *InviteUpdateOne {
	_u.mutation.ClearChallengeExpiresAt()
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *InviteUpdateOne) SetUserAgent(v string) *InviteUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableUserAgent(v *string) *InviteUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *InviteUpdateOne) SetIP(v string) *InviteUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableIP(v *string) *InviteUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *InviteUpdateOne) SetUserID(v uuid.UUID) *InviteUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *InviteUpdateOne) SetNillableUserID(v *uuid.UUID) *InviteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "userID" field.
func (_u *InviteUpdateOne) ClearUserID() *InviteUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InviteUpdateOne) SetUser(v *User) *InviteUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_u *InviteUpdateOne) Mutation() *InviteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InviteUpdateOne) ClearUser() *InviteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InviteUpdate builder.
func (_u *InviteUpdateOne) Where(ps ...predicate.Invite) *InviteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteUpdateOne) Select(field string, fields ...string) *InviteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invite entity.
func (_u *InviteUpdateOne) Save(ctx context.Context) (*Invite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteUpdateOne) SaveX(ctx context.Context) *Invite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedCode(); ok {
		if err := invite.HashedCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedCode", err: fmt.Errorf(`ent: validator failed for field "Invite.hashedCode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpiredReason(); ok {
		if err := invite.ExpiredReasonValidator(v); err != nil {
			return &ValidationError{Name: "expiredReason", err: fmt.Errorf(`ent: validator failed for field "Invite.expiredReason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebauthnChallenge(); ok {
		if err := invite.WebauthnChallengeValidator(v); err != nil {
			return &ValidationError{Name: "webauthnChallenge", err: fmt.Errorf(`ent: validator failed for field "Invite.webauthnChallenge": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteUpdateOne) sqlSave(ctx context.Context) (_node *Invite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invite.FieldID)
		for _, f := range fields {
			if !invite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invite.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedCode(); ok {
		_spec.SetField(invite.FieldHashedCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredReason(); ok {
		_spec.SetField(invite.FieldExpiredReason, field.TypeEnum, value)
	}
	if _u.mutation.ExpiredReasonCleared() {
		_spec.ClearField(invite.FieldExpiredReason, field.TypeEnum)
	}
	if value, ok := _u.mutation.WebauthnChallenge(); ok {
		_spec.SetField(invite.FieldWebauthnChallenge, field.TypeBytes, value)
	}
	if _u.mutation.WebauthnChallengeCleared() {
		_spec.ClearField(invite.FieldWebauthnChallenge, field.TypeBytes)
	}
	if value, ok := _u.mutation.ChallengeExpiresAt(); ok {
		_spec.SetField(invite.FieldChallengeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ChallengeExpiresAtCleared() {
		_spec.ClearField(invite.FieldChallengeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(invite.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(invite.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invite.UserTable,
			Columns: []string{invite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invite.UserTable,
			Columns: []string{invite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
