// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NicoClack/cryptic-stash/backend/ent/downloadsession"
	"github.com/NicoClack/cryptic-stash/backend/ent/loginalert"
	"github.com/NicoClack/cryptic-stash/backend/ent/usermessenger"
	"github.com/google/uuid"
)

// LoginAlert is the model entity for the LoginAlert schema.
type LoginAlert struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SentAt holds the value of the "sentAt" field.
	SentAt time.Time `json:"sentAt,omitempty"`
	// Confirmed holds the value of the "confirmed" field.
	Confirmed bool `json:"confirmed,omitempty"`
	// DownloadSessionID holds the value of the "downloadSessionID" field.
	DownloadSessionID uuid.UUID `json:"downloadSessionID,omitempty"`
	// UserMessengerID holds the value of the "userMessengerID" field.
	UserMessengerID uuid.UUID `json:"userMessengerID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginAlertQuery when eager-loading is set.
	Edges        LoginAlertEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LoginAlertEdges holds the relations/edges for other nodes in the graph.
type LoginAlertEdges struct {
	// DownloadSession holds the value of the downloadSession edge.
	DownloadSession *DownloadSession `json:"downloadSession,omitempty"`
	// UserMessenger holds the value of the userMessenger edge.
	UserMessenger *UserMessenger `json:"userMessenger,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DownloadSessionOrErr returns the DownloadSession value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginAlertEdges) DownloadSessionOrErr() (*DownloadSession, error) {
	if e.DownloadSession != nil {
		return e.DownloadSession, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: downloadsession.Label}
	}
	return nil, &NotLoadedError{edge: "downloadSession"}
}

// UserMessengerOrErr returns the UserMessenger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginAlertEdges) UserMessengerOrErr() (*UserMessenger, error) {
	if e.UserMessenger != nil {
		return e.UserMessenger, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usermessenger.Label}
	}
	return nil, &NotLoadedError{edge: "userMessenger"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginAlert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginalert.FieldConfirmed:
			values[i] = new(sql.NullBool)
		case loginalert.FieldSentAt:
			values[i] = new(sql.NullTime)
		case loginalert.FieldID, loginalert.FieldDownloadSessionID, loginalert.FieldUserMessengerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginAlert fields.
func (_m *LoginAlert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginalert.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case loginalert.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sentAt", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		case loginalert.FieldConfirmed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed", values[i])
			} else if value.Valid {
				_m.Confirmed = value.Bool
			}
		case loginalert.FieldDownloadSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field downloadSessionID", values[i])
			} else if value != nil {
				_m.DownloadSessionID = *value
			}
		case loginalert.FieldUserMessengerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field userMessengerID", values[i])
			} else if value != nil {
				_m.UserMessengerID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginAlert.
// This includes values selected through modifiers, order, etc.
func (_m *LoginAlert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDownloadSession queries the "downloadSession" edge of the LoginAlert entity.
func (_m *LoginAlert) QueryDownloadSession() *DownloadSessionQuery {
	return NewLoginAlertClient(_m.config).QueryDownloadSession(_m)
}

// QueryUserMessenger queries the "userMessenger" edge of the LoginAlert entity.
func (_m *LoginAlert) QueryUserMessenger() *UserMessengerQuery {
	return NewLoginAlertClient(_m.config).QueryUserMessenger(_m)
}

// Update returns a builder for updating this LoginAlert.
// Note that you need to call LoginAlert.Unwrap() before calling this method if this LoginAlert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoginAlert) Update() *LoginAlertUpdateOne {
	return NewLoginAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoginAlert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoginAlert) Unwrap() *LoginAlert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginAlert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoginAlert) String() string {
	var builder strings.Builder
	builder.WriteString("LoginAlert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sentAt=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("confirmed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confirmed))
	builder.WriteString(", ")
	builder.WriteString("downloadSessionID=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadSessionID))
	builder.WriteString(", ")
	builder.WriteString("userMessengerID=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserMessengerID))
	builder.WriteByte(')')
	return builder.String()
}

// LoginAlerts is a parsable slice of LoginAlert.
type LoginAlerts []*LoginAlert
