// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/passkey"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/NicoClack/cryptic-stash/backend/ent/session"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

// PasskeyUpdate is the builder for updating Passkey entities.
type PasskeyUpdate struct {
	config
	hooks    []Hook
	mutation *PasskeyMutation
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (_u *PasskeyUpdate) Where(ps ...predicate.Passkey) *PasskeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *PasskeyUpdate) SetCreatedAt(v time.Time) *PasskeyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableCreatedAt(v *time.Time) *PasskeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PasskeyUpdate) SetUpdatedAt(v time.Time) *PasskeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastUsedAt sets the "lastUsedAt" field.
func (_u *PasskeyUpdate) SetLastUsedAt(v time.Time) *PasskeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "lastUsedAt" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableLastUsedAt(v *time.Time) *PasskeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "lastUsedAt" field.
func (_u *PasskeyUpdate) ClearLastUsedAt() *PasskeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PasskeyUpdate) SetName(v string) *PasskeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableName(v *string) *PasskeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAllowSudo sets the "allowSudo" field.
func (_u *PasskeyUpdate) SetAllowSudo(v bool) *PasskeyUpdate {
	_u.mutation.SetAllowSudo(v)
	return _u
}

// SetNillableAllowSudo sets the "allowSudo" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableAllowSudo(v *bool) *PasskeyUpdate {
	if v != nil {
		_u.SetAllowSudo(*v)
	}
	return _u
}

// SetCredentialID sets the "credentialID" field.
func (_u *PasskeyUpdate) SetCredentialID(v []byte) *PasskeyUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetCredential sets the "credential" field.
func (_u *PasskeyUpdate) SetCredential(v webauthn.Credential) *PasskeyUpdate {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableCredential(v *webauthn.Credential) *PasskeyUpdate {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (_u *PasskeyUpdate) SetIsSecondGroup(v bool) *PasskeyUpdate {
	_u.mutation.SetIsSecondGroup(v)
	return _u
}

// SetNillableIsSecondGroup sets the "isSecondGroup" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableIsSecondGroup(v *bool) *PasskeyUpdate {
	if v != nil {
		_u.SetIsSecondGroup(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *PasskeyUpdate) SetUserID(v uuid.UUID) *PasskeyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *PasskeyUpdate) SetNillableUserID(v *uuid.UUID) *PasskeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyUpdate) SetUser(v *User) *PasskeyUpdate {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *PasskeyUpdate) AddSessionIDs(ids ...uuid.UUID) *PasskeyUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *PasskeyUpdate) AddSessions(v ...*Session) *PasskeyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddElevatedSessionIDs adds the "elevatedSessions" edge to the Session entity by IDs.
func (_u *PasskeyUpdate) AddElevatedSessionIDs(ids ...uuid.UUID) *PasskeyUpdate {
	_u.mutation.AddElevatedSessionIDs(ids...)
	return _u
}

// AddElevatedSessions adds the "elevatedSessions" edges to the Session entity.
func (_u *PasskeyUpdate) AddElevatedSessions(v ...*Session) *PasskeyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddElevatedSessionIDs(ids...)
}

// Mutation returns the PasskeyMutation object of the builder.
func (_u *PasskeyUpdate) Mutation() *PasskeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyUpdate) ClearUser() *PasskeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *PasskeyUpdate) ClearSessions() *PasskeyUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *PasskeyUpdate) RemoveSessionIDs(ids ...uuid.UUID) *PasskeyUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *PasskeyUpdate) RemoveSessions(v ...*Session) *PasskeyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearElevatedSessions clears all "elevatedSessions" edges to the Session entity.
func (_u *PasskeyUpdate) ClearElevatedSessions() *PasskeyUpdate {
	_u.mutation.ClearElevatedSessions()
	return _u
}

// RemoveElevatedSessionIDs removes the "elevatedSessions" edge to Session entities by IDs.
func (_u *PasskeyUpdate) RemoveElevatedSessionIDs(ids ...uuid.UUID) *PasskeyUpdate {
	_u.mutation.RemoveElevatedSessionIDs(ids...)
	return _u
}

// RemoveElevatedSessions removes "elevatedSessions" edges to Session entities.
func (_u *PasskeyUpdate) RemoveElevatedSessions(v ...*Session) *PasskeyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveElevatedSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasskeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasskeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := passkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Passkey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := passkey.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credentialID", err: fmt.Errorf(`ent: validator failed for field "Passkey.credentialID": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (_u *PasskeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(passkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(passkey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(passkey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(passkey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowSudo(); ok {
		_spec.SetField(passkey.FieldAllowSudo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Credential(); ok {
		vv, err := passkey.ValueScanner.Credential.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(passkey.FieldCredential, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.IsSecondGroup(); ok {
		_spec.SetField(passkey.FieldIsSecondGroup, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElevatedSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedElevatedSessionsIDs(); len(nodes) > 0 && !_u.mutation.ElevatedSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElevatedSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasskeyUpdateOne is the builder for updating a single Passkey entity.
type PasskeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasskeyMutation
}

// SetCreatedAt sets the "createdAt" field.
func (_u *PasskeyUpdateOne) SetCreatedAt(v time.Time) *PasskeyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableCreatedAt(v *time.Time) *PasskeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PasskeyUpdateOne) SetUpdatedAt(v time.Time) *PasskeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastUsedAt sets the "lastUsedAt" field.
func (_u *PasskeyUpdateOne) SetLastUsedAt(v time.Time) *PasskeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "lastUsedAt" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *PasskeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "lastUsedAt" field.
func (_u *PasskeyUpdateOne) ClearLastUsedAt() *PasskeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PasskeyUpdateOne) SetName(v string) *PasskeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableName(v *string) *PasskeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAllowSudo sets the "allowSudo" field.
func (_u *PasskeyUpdateOne) SetAllowSudo(v bool) *PasskeyUpdateOne {
	_u.mutation.SetAllowSudo(v)
	return _u
}

// SetNillableAllowSudo sets the "allowSudo" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableAllowSudo(v *bool) *PasskeyUpdateOne {
	if v != nil {
		_u.SetAllowSudo(*v)
	}
	return _u
}

// SetCredentialID sets the "credentialID" field.
func (_u *PasskeyUpdateOne) SetCredentialID(v []byte) *PasskeyUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetCredential sets the "credential" field.
func (_u *PasskeyUpdateOne) SetCredential(v webauthn.Credential) *PasskeyUpdateOne {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableCredential(v *webauthn.Credential) *PasskeyUpdateOne {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (_u *PasskeyUpdateOne) SetIsSecondGroup(v bool) *PasskeyUpdateOne {
	_u.mutation.SetIsSecondGroup(v)
	return _u
}

// SetNillableIsSecondGroup sets the "isSecondGroup" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableIsSecondGroup(v *bool) *PasskeyUpdateOne {
	if v != nil {
		_u.SetIsSecondGroup(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *PasskeyUpdateOne) SetUserID(v uuid.UUID) *PasskeyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *PasskeyUpdateOne) SetNillableUserID(v *uuid.UUID) *PasskeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyUpdateOne) SetUser(v *User) *PasskeyUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_u *PasskeyUpdateOne) AddSessionIDs(ids ...uuid.UUID) *PasskeyUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_u *PasskeyUpdateOne) AddSessions(v ...*Session) *PasskeyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddElevatedSessionIDs adds the "elevatedSessions" edge to the Session entity by IDs.
func (_u *PasskeyUpdateOne) AddElevatedSessionIDs(ids ...uuid.UUID) *PasskeyUpdateOne {
	_u.mutation.AddElevatedSessionIDs(ids...)
	return _u
}

// AddElevatedSessions adds the "elevatedSessions" edges to the Session entity.
func (_u *PasskeyUpdateOne) AddElevatedSessions(v ...*Session) *PasskeyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddElevatedSessionIDs(ids...)
}

// Mutation returns the PasskeyMutation object of the builder.
func (_u *PasskeyUpdateOne) Mutation() *PasskeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyUpdateOne) ClearUser() *PasskeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the Session entity.
func (_u *PasskeyUpdateOne) ClearSessions() *PasskeyUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Session entities by IDs.
func (_u *PasskeyUpdateOne) RemoveSessionIDs(ids ...uuid.UUID) *PasskeyUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Session entities.
func (_u *PasskeyUpdateOne) RemoveSessions(v ...*Session) *PasskeyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearElevatedSessions clears all "elevatedSessions" edges to the Session entity.
func (_u *PasskeyUpdateOne) ClearElevatedSessions() *PasskeyUpdateOne {
	_u.mutation.ClearElevatedSessions()
	return _u
}

// RemoveElevatedSessionIDs removes the "elevatedSessions" edge to Session entities by IDs.
func (_u *PasskeyUpdateOne) RemoveElevatedSessionIDs(ids ...uuid.UUID) *PasskeyUpdateOne {
	_u.mutation.RemoveElevatedSessionIDs(ids...)
	return _u
}

// RemoveElevatedSessions removes "elevatedSessions" edges to Session entities.
func (_u *PasskeyUpdateOne) RemoveElevatedSessions(v ...*Session) *PasskeyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveElevatedSessionIDs(ids...)
}

// Where appends a list predicates to the PasskeyUpdate builder.
func (_u *PasskeyUpdateOne) Where(ps ...predicate.Passkey) *PasskeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasskeyUpdateOne) Select(field string, fields ...string) *PasskeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Passkey entity.
func (_u *PasskeyUpdateOne) Save(ctx context.Context) (*Passkey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUpdateOne) SaveX(ctx context.Context) *Passkey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasskeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := passkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Passkey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialID(); ok {
		if err := passkey.CredentialIDValidator(v); err != nil {
			return &ValidationError{Name: "credentialID", err: fmt.Errorf(`ent: validator failed for field "Passkey.credentialID": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Passkey.user"`)
	}
	return nil
}

func (_u *PasskeyUpdateOne) sqlSave(ctx context.Context) (_node *Passkey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkey.Table, passkey.Columns, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Passkey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passkey.FieldID)
		for _, f := range fields {
			if !passkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(passkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(passkey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(passkey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(passkey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AllowSudo(); ok {
		_spec.SetField(passkey.FieldAllowSudo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Credential(); ok {
		vv, err := passkey.ValueScanner.Credential.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(passkey.FieldCredential, field.TypeBytes, vv)
	}
	if value, ok := _u.mutation.IsSecondGroup(); ok {
		_spec.SetField(passkey.FieldIsSecondGroup, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ElevatedSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedElevatedSessionsIDs(); len(nodes) > 0 && !_u.mutation.ElevatedSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ElevatedSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.ElevatedSessionsTable,
			Columns: []string{passkey.ElevatedSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Passkey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
