// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/passkey"
	"github.com/NicoClack/cryptic-stash/backend/ent/session"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// PasskeyCreate is the builder for creating a Passkey entity.
type PasskeyCreate struct {
	config
	mutation *PasskeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "createdAt" field.
func (_c *PasskeyCreate) SetCreatedAt(v time.Time) *PasskeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *PasskeyCreate) SetUpdatedAt(v time.Time) *PasskeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PasskeyCreate) SetName(v string) *PasskeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCredentialID sets the "credentialID" field.
func (_c *PasskeyCreate) SetCredentialID(v []byte) *PasskeyCreate {
	_c.mutation.SetCredentialID(v)
	return _c
}

// SetPublicKey sets the "publicKey" field.
func (_c *PasskeyCreate) SetPublicKey(v []byte) *PasskeyCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetAaguid sets the "aaguid" field.
func (_c *PasskeyCreate) SetAaguid(v uuid.UUID) *PasskeyCreate {
	_c.mutation.SetAaguid(v)
	return _c
}

// SetNillableAaguid sets the "aaguid" field if the given value is not nil.
func (_c *PasskeyCreate) SetNillableAaguid(v *uuid.UUID) *PasskeyCreate {
	if v != nil {
		_c.SetAaguid(*v)
	}
	return _c
}

// SetSignCount sets the "signCount" field.
func (_c *PasskeyCreate) SetSignCount(v uint32) *PasskeyCreate {
	_c.mutation.SetSignCount(v)
	return _c
}

// SetNillableSignCount sets the "signCount" field if the given value is not nil.
func (_c *PasskeyCreate) SetNillableSignCount(v *uint32) *PasskeyCreate {
	if v != nil {
		_c.SetSignCount(*v)
	}
	return _c
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (_c *PasskeyCreate) SetIsSecondGroup(v bool) *PasskeyCreate {
	_c.mutation.SetIsSecondGroup(v)
	return _c
}

// SetNillableIsSecondGroup sets the "isSecondGroup" field if the given value is not nil.
func (_c *PasskeyCreate) SetNillableIsSecondGroup(v *bool) *PasskeyCreate {
	if v != nil {
		_c.SetIsSecondGroup(*v)
	}
	return _c
}

// SetUserID sets the "userID" field.
func (_c *PasskeyCreate) SetUserID(v uuid.UUID) *PasskeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PasskeyCreate) SetID(v uuid.UUID) *PasskeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PasskeyCreate) SetNillableID(v *uuid.UUID) *PasskeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PasskeyCreate) SetUser(v *User) *PasskeyCreate {
	return _c.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_c *PasskeyCreate) AddSessionIDs(ids ...uuid.UUID) *PasskeyCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_c *PasskeyCreate) AddSessions(v ...*Session) *PasskeyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// Mutation returns the PasskeyMutation object of the builder.
func (_c *PasskeyCreate) Mutation() *PasskeyMutation {
	return _c.mutation
}

// Save creates the Passkey in the database.
func (_c *PasskeyCreate) Save(ctx context.Context) (*Passkey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasskeyCreate) SaveX(ctx context.Context) *Passkey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PasskeyCreate) defaults() {
	if _, ok := _c.mutation.SignCount(); !ok {
		v := passkey.DefaultSignCount
		_c.mutation.SetSignCount(v)
	}
	if _, ok := _c.mutation.IsSecondGroup(); !ok {
		v := passkey.DefaultIsSecondGroup
		_c.mutation.SetIsSecondGroup(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := passkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasskeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Passkey.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Passkey.updatedAt"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Passkey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := passkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Passkey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CredentialID(); !ok {
		return &ValidationError{Name: "credentialID", err: errors.New(`ent: missing required field "Passkey.credentialID"`)}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "publicKey", err: errors.New(`ent: missing required field "Passkey.publicKey"`)}
	}
	if _, ok := _c.mutation.SignCount(); !ok {
		return &ValidationError{Name: "signCount", err: errors.New(`ent: missing required field "Passkey.signCount"`)}
	}
	if _, ok := _c.mutation.IsSecondGroup(); !ok {
		return &ValidationError{Name: "isSecondGroup", err: errors.New(`ent: missing required field "Passkey.isSecondGroup"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "userID", err: errors.New(`ent: missing required field "Passkey.userID"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Passkey.user"`)}
	}
	return nil
}

func (_c *PasskeyCreate) sqlSave(ctx context.Context) (*Passkey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasskeyCreate) createSpec() (*Passkey, *sqlgraph.CreateSpec) {
	var (
		_node = &Passkey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passkey.Table, sqlgraph.NewFieldSpec(passkey.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(passkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(passkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CredentialID(); ok {
		_spec.SetField(passkey.FieldCredentialID, field.TypeBytes, value)
		_node.CredentialID = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(passkey.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.Aaguid(); ok {
		_spec.SetField(passkey.FieldAaguid, field.TypeUUID, value)
		_node.Aaguid = value
	}
	if value, ok := _c.mutation.SignCount(); ok {
		_spec.SetField(passkey.FieldSignCount, field.TypeUint32, value)
		_node.SignCount = value
	}
	if value, ok := _c.mutation.IsSecondGroup(); ok {
		_spec.SetField(passkey.FieldIsSecondGroup, field.TypeBool, value)
		_node.IsSecondGroup = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkey.UserTable,
			Columns: []string{passkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passkey.SessionsTable,
			Columns: []string{passkey.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Passkey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCreate) OnConflict(opts ...sql.ConflictOption) *PasskeyUpsertOne {
	_c.conflict = opts
	return &PasskeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Passkey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCreate) OnConflictColumns(columns ...string) *PasskeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyUpsertOne{
		create: _c,
	}
}

type (
	// PasskeyUpsertOne is the builder for "upsert"-ing
	//  one Passkey node.
	PasskeyUpsertOne struct {
		create *PasskeyCreate
	}

	// PasskeyUpsert is the "OnConflict" setter.
	PasskeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "createdAt" field.
func (u *PasskeyUpsert) SetCreatedAt(v time.Time) *PasskeyUpsert {
	u.Set(passkey.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateCreatedAt() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *PasskeyUpsert) SetUpdatedAt(v time.Time) *PasskeyUpsert {
	u.Set(passkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateUpdatedAt() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *PasskeyUpsert) SetName(v string) *PasskeyUpsert {
	u.Set(passkey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateName() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldName)
	return u
}

// SetCredentialID sets the "credentialID" field.
func (u *PasskeyUpsert) SetCredentialID(v []byte) *PasskeyUpsert {
	u.Set(passkey.FieldCredentialID, v)
	return u
}

// UpdateCredentialID sets the "credentialID" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateCredentialID() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldCredentialID)
	return u
}

// SetPublicKey sets the "publicKey" field.
func (u *PasskeyUpsert) SetPublicKey(v []byte) *PasskeyUpsert {
	u.Set(passkey.FieldPublicKey, v)
	return u
}

// UpdatePublicKey sets the "publicKey" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdatePublicKey() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldPublicKey)
	return u
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyUpsert) SetAaguid(v uuid.UUID) *PasskeyUpsert {
	u.Set(passkey.FieldAaguid, v)
	return u
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateAaguid() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldAaguid)
	return u
}

// ClearAaguid clears the value of the "aaguid" field.
func (u *PasskeyUpsert) ClearAaguid() *PasskeyUpsert {
	u.SetNull(passkey.FieldAaguid)
	return u
}

// SetSignCount sets the "signCount" field.
func (u *PasskeyUpsert) SetSignCount(v uint32) *PasskeyUpsert {
	u.Set(passkey.FieldSignCount, v)
	return u
}

// UpdateSignCount sets the "signCount" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateSignCount() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldSignCount)
	return u
}

// AddSignCount adds v to the "signCount" field.
func (u *PasskeyUpsert) AddSignCount(v uint32) *PasskeyUpsert {
	u.Add(passkey.FieldSignCount, v)
	return u
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (u *PasskeyUpsert) SetIsSecondGroup(v bool) *PasskeyUpsert {
	u.Set(passkey.FieldIsSecondGroup, v)
	return u
}

// UpdateIsSecondGroup sets the "isSecondGroup" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateIsSecondGroup() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldIsSecondGroup)
	return u
}

// SetUserID sets the "userID" field.
func (u *PasskeyUpsert) SetUserID(v uuid.UUID) *PasskeyUpsert {
	u.Set(passkey.FieldUserID, v)
	return u
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *PasskeyUpsert) UpdateUserID() *PasskeyUpsert {
	u.SetExcluded(passkey.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Passkey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeyUpsertOne) UpdateNewValues() *PasskeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(passkey.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Passkey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasskeyUpsertOne) Ignore() *PasskeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyUpsertOne) DoNothing() *PasskeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCreate.OnConflict
// documentation for more info.
func (u *PasskeyUpsertOne) Update(set func(*PasskeyUpsert)) *PasskeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "createdAt" field.
func (u *PasskeyUpsertOne) SetCreatedAt(v time.Time) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateCreatedAt() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *PasskeyUpsertOne) SetUpdatedAt(v time.Time) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateUpdatedAt() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PasskeyUpsertOne) SetName(v string) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateName() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateName()
	})
}

// SetCredentialID sets the "credentialID" field.
func (u *PasskeyUpsertOne) SetCredentialID(v []byte) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credentialID" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateCredentialID() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateCredentialID()
	})
}

// SetPublicKey sets the "publicKey" field.
func (u *PasskeyUpsertOne) SetPublicKey(v []byte) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "publicKey" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdatePublicKey() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdatePublicKey()
	})
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyUpsertOne) SetAaguid(v uuid.UUID) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetAaguid(v)
	})
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateAaguid() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateAaguid()
	})
}

// ClearAaguid clears the value of the "aaguid" field.
func (u *PasskeyUpsertOne) ClearAaguid() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.ClearAaguid()
	})
}

// SetSignCount sets the "signCount" field.
func (u *PasskeyUpsertOne) SetSignCount(v uint32) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "signCount" field.
func (u *PasskeyUpsertOne) AddSignCount(v uint32) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "signCount" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateSignCount() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateSignCount()
	})
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (u *PasskeyUpsertOne) SetIsSecondGroup(v bool) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetIsSecondGroup(v)
	})
}

// UpdateIsSecondGroup sets the "isSecondGroup" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateIsSecondGroup() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateIsSecondGroup()
	})
}

// SetUserID sets the "userID" field.
func (u *PasskeyUpsertOne) SetUserID(v uuid.UUID) *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *PasskeyUpsertOne) UpdateUserID() *PasskeyUpsertOne {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *PasskeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasskeyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PasskeyUpsertOne.ID is not supported by MySQL driver. Use PasskeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasskeyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasskeyCreateBulk is the builder for creating many Passkey entities in bulk.
type PasskeyCreateBulk struct {
	config
	err      error
	builders []*PasskeyCreate
	conflict []sql.ConflictOption
}

// Save creates the Passkey entities in the database.
func (_c *PasskeyCreateBulk) Save(ctx context.Context) ([]*Passkey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Passkey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasskeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasskeyCreateBulk) SaveX(ctx context.Context) []*Passkey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Passkey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasskeyUpsertBulk {
	_c.conflict = opts
	return &PasskeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Passkey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCreateBulk) OnConflictColumns(columns ...string) *PasskeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyUpsertBulk{
		create: _c,
	}
}

// PasskeyUpsertBulk is the builder for "upsert"-ing
// a bulk of Passkey nodes.
type PasskeyUpsertBulk struct {
	create *PasskeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Passkey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeyUpsertBulk) UpdateNewValues() *PasskeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(passkey.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Passkey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasskeyUpsertBulk) Ignore() *PasskeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyUpsertBulk) DoNothing() *PasskeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCreateBulk.OnConflict
// documentation for more info.
func (u *PasskeyUpsertBulk) Update(set func(*PasskeyUpsert)) *PasskeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "createdAt" field.
func (u *PasskeyUpsertBulk) SetCreatedAt(v time.Time) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateCreatedAt() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *PasskeyUpsertBulk) SetUpdatedAt(v time.Time) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateUpdatedAt() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PasskeyUpsertBulk) SetName(v string) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateName() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateName()
	})
}

// SetCredentialID sets the "credentialID" field.
func (u *PasskeyUpsertBulk) SetCredentialID(v []byte) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetCredentialID(v)
	})
}

// UpdateCredentialID sets the "credentialID" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateCredentialID() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateCredentialID()
	})
}

// SetPublicKey sets the "publicKey" field.
func (u *PasskeyUpsertBulk) SetPublicKey(v []byte) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "publicKey" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdatePublicKey() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdatePublicKey()
	})
}

// SetAaguid sets the "aaguid" field.
func (u *PasskeyUpsertBulk) SetAaguid(v uuid.UUID) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetAaguid(v)
	})
}

// UpdateAaguid sets the "aaguid" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateAaguid() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateAaguid()
	})
}

// ClearAaguid clears the value of the "aaguid" field.
func (u *PasskeyUpsertBulk) ClearAaguid() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.ClearAaguid()
	})
}

// SetSignCount sets the "signCount" field.
func (u *PasskeyUpsertBulk) SetSignCount(v uint32) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "signCount" field.
func (u *PasskeyUpsertBulk) AddSignCount(v uint32) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "signCount" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateSignCount() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateSignCount()
	})
}

// SetIsSecondGroup sets the "isSecondGroup" field.
func (u *PasskeyUpsertBulk) SetIsSecondGroup(v bool) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetIsSecondGroup(v)
	})
}

// UpdateIsSecondGroup sets the "isSecondGroup" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateIsSecondGroup() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateIsSecondGroup()
	})
}

// SetUserID sets the "userID" field.
func (u *PasskeyUpsertBulk) SetUserID(v uuid.UUID) *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *PasskeyUpsertBulk) UpdateUserID() *PasskeyUpsertBulk {
	return u.Update(func(s *PasskeyUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *PasskeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasskeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
