// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NicoClack/cryptic-stash/backend/ent/signuplink"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// SignupLink is the model entity for the SignupLink schema.
type SignupLink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Code holds the value of the "code" field.
	Code []byte `json:"code,omitempty"`
	// ExpiresAt holds the value of the "expiresAt" field.
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	// UserAgent holds the value of the "userAgent" field.
	UserAgent string `json:"userAgent,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// UserID holds the value of the "userID" field.
	UserID uuid.UUID `json:"userID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SignupLinkQuery when eager-loading is set.
	Edges        SignupLinkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SignupLinkEdges holds the relations/edges for other nodes in the graph.
type SignupLinkEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SignupLinkEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SignupLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case signuplink.FieldCode:
			values[i] = new([]byte)
		case signuplink.FieldName, signuplink.FieldUserAgent, signuplink.FieldIP:
			values[i] = new(sql.NullString)
		case signuplink.FieldCreatedAt, signuplink.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case signuplink.FieldID, signuplink.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SignupLink fields.
func (_m *SignupLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case signuplink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case signuplink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case signuplink.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case signuplink.FieldCode:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value != nil {
				_m.Code = *value
			}
		case signuplink.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case signuplink.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userAgent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case signuplink.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case signuplink.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field userID", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SignupLink.
// This includes values selected through modifiers, order, etc.
func (_m *SignupLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SignupLink entity.
func (_m *SignupLink) QueryUser() *UserQuery {
	return NewSignupLinkClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this SignupLink.
// Note that you need to call SignupLink.Unwrap() before calling this method if this SignupLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SignupLink) Update() *SignupLinkUpdateOne {
	return NewSignupLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SignupLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SignupLink) Unwrap() *SignupLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SignupLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SignupLink) String() string {
	var builder strings.Builder
	builder.WriteString("SignupLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(fmt.Sprintf("%v", _m.Code))
	builder.WriteString(", ")
	builder.WriteString("expiresAt=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("userAgent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("userID=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// SignupLinks is a parsable slice of SignupLink.
type SignupLinks []*SignupLink
