// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/NicoClack/cryptic-stash/backend/ent/signuplink"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// SignupLinkUpdate is the builder for updating SignupLink entities.
type SignupLinkUpdate struct {
	config
	hooks    []Hook
	mutation *SignupLinkMutation
}

// Where appends a list predicates to the SignupLinkUpdate builder.
func (_u *SignupLinkUpdate) Where(ps ...predicate.SignupLink) *SignupLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *SignupLinkUpdate) SetCreatedAt(v time.Time) *SignupLinkUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableCreatedAt(v *time.Time) *SignupLinkUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SignupLinkUpdate) SetName(v string) *SignupLinkUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableName(v *string) *SignupLinkUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHashedCode sets the "hashedCode" field.
func (_u *SignupLinkUpdate) SetHashedCode(v []byte) *SignupLinkUpdate {
	_u.mutation.SetHashedCode(v)
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *SignupLinkUpdate) SetExpiresAt(v time.Time) *SignupLinkUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableExpiresAt(v *time.Time) *SignupLinkUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *SignupLinkUpdate) SetUserAgent(v string) *SignupLinkUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableUserAgent(v *string) *SignupLinkUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *SignupLinkUpdate) SetIP(v string) *SignupLinkUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableIP(v *string) *SignupLinkUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *SignupLinkUpdate) SetUserID(v uuid.UUID) *SignupLinkUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *SignupLinkUpdate) SetNillableUserID(v *uuid.UUID) *SignupLinkUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "userID" field.
func (_u *SignupLinkUpdate) ClearUserID() *SignupLinkUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SignupLinkUpdate) SetUser(v *User) *SignupLinkUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SignupLinkMutation object of the builder.
func (_u *SignupLinkUpdate) Mutation() *SignupLinkMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SignupLinkUpdate) ClearUser() *SignupLinkUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SignupLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignupLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SignupLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignupLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignupLinkUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := signuplink.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SignupLink.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedCode(); ok {
		if err := signuplink.HashedCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedCode", err: fmt.Errorf(`ent: validator failed for field "SignupLink.hashedCode": %w`, err)}
		}
	}
	return nil
}

func (_u *SignupLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signuplink.Table, signuplink.Columns, sqlgraph.NewFieldSpec(signuplink.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(signuplink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(signuplink.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedCode(); ok {
		_spec.SetField(signuplink.FieldHashedCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(signuplink.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(signuplink.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(signuplink.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   signuplink.UserTable,
			Columns: []string{signuplink.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   signuplink.UserTable,
			Columns: []string{signuplink.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signuplink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SignupLinkUpdateOne is the builder for updating a single SignupLink entity.
type SignupLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignupLinkMutation
}

// SetCreatedAt sets the "createdAt" field.
func (_u *SignupLinkUpdateOne) SetCreatedAt(v time.Time) *SignupLinkUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableCreatedAt(v *time.Time) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SignupLinkUpdateOne) SetName(v string) *SignupLinkUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableName(v *string) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHashedCode sets the "hashedCode" field.
func (_u *SignupLinkUpdateOne) SetHashedCode(v []byte) *SignupLinkUpdateOne {
	_u.mutation.SetHashedCode(v)
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *SignupLinkUpdateOne) SetExpiresAt(v time.Time) *SignupLinkUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableExpiresAt(v *time.Time) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserAgent sets the "userAgent" field.
func (_u *SignupLinkUpdateOne) SetUserAgent(v string) *SignupLinkUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableUserAgent(v *string) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *SignupLinkUpdateOne) SetIP(v string) *SignupLinkUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableIP(v *string) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetUserID sets the "userID" field.
func (_u *SignupLinkUpdateOne) SetUserID(v uuid.UUID) *SignupLinkUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *SignupLinkUpdateOne) SetNillableUserID(v *uuid.UUID) *SignupLinkUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "userID" field.
func (_u *SignupLinkUpdateOne) ClearUserID() *SignupLinkUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SignupLinkUpdateOne) SetUser(v *User) *SignupLinkUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SignupLinkMutation object of the builder.
func (_u *SignupLinkUpdateOne) Mutation() *SignupLinkMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SignupLinkUpdateOne) ClearUser() *SignupLinkUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SignupLinkUpdate builder.
func (_u *SignupLinkUpdateOne) Where(ps ...predicate.SignupLink) *SignupLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SignupLinkUpdateOne) Select(field string, fields ...string) *SignupLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SignupLink entity.
func (_u *SignupLinkUpdateOne) Save(ctx context.Context) (*SignupLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignupLinkUpdateOne) SaveX(ctx context.Context) *SignupLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SignupLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignupLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignupLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := signuplink.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SignupLink.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedCode(); ok {
		if err := signuplink.HashedCodeValidator(v); err != nil {
			return &ValidationError{Name: "hashedCode", err: fmt.Errorf(`ent: validator failed for field "SignupLink.hashedCode": %w`, err)}
		}
	}
	return nil
}

func (_u *SignupLinkUpdateOne) sqlSave(ctx context.Context) (_node *SignupLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signuplink.Table, signuplink.Columns, sqlgraph.NewFieldSpec(signuplink.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SignupLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signuplink.FieldID)
		for _, f := range fields {
			if !signuplink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signuplink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(signuplink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(signuplink.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedCode(); ok {
		_spec.SetField(signuplink.FieldHashedCode, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(signuplink.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(signuplink.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(signuplink.FieldIP, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   signuplink.UserTable,
			Columns: []string{signuplink.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   signuplink.UserTable,
			Columns: []string{signuplink.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SignupLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signuplink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
