// Code generated by ent, DO NOT EDIT.

package downloadsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the downloadsession type in the database.
	Label = "download_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldHashedAuthCode holds the string denoting the hashedauthcode field in the database.
	FieldHashedAuthCode = "hashed_auth_code"
	// FieldValidFrom holds the string denoting the validfrom field in the database.
	FieldValidFrom = "valid_from"
	// FieldValidUntil holds the string denoting the validuntil field in the database.
	FieldValidUntil = "valid_until"
	// FieldUserAgent holds the string denoting the useragent field in the database.
	FieldUserAgent = "user_agent"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldStashID holds the string denoting the stashid field in the database.
	FieldStashID = "stash_id"
	// EdgeStash holds the string denoting the stash edge name in mutations.
	EdgeStash = "stash"
	// EdgeLoginAlerts holds the string denoting the loginalerts edge name in mutations.
	EdgeLoginAlerts = "loginAlerts"
	// Table holds the table name of the downloadsession in the database.
	Table = "download_sessions"
	// StashTable is the table that holds the stash relation/edge.
	StashTable = "download_sessions"
	// StashInverseTable is the table name for the Stash entity.
	// It exists in this package in order to avoid circular dependency with the "stash" package.
	StashInverseTable = "stashes"
	// StashColumn is the table column denoting the stash relation/edge.
	StashColumn = "stash_id"
	// LoginAlertsTable is the table that holds the loginAlerts relation/edge.
	LoginAlertsTable = "login_alerts"
	// LoginAlertsInverseTable is the table name for the LoginAlert entity.
	// It exists in this package in order to avoid circular dependency with the "loginalert" package.
	LoginAlertsInverseTable = "login_alerts"
	// LoginAlertsColumn is the table column denoting the loginAlerts relation/edge.
	LoginAlertsColumn = "download_session_id"
)

// Columns holds all SQL columns for downloadsession fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldHashedAuthCode,
	FieldValidFrom,
	FieldValidUntil,
	FieldUserAgent,
	FieldIP,
	FieldStashID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// HashedAuthCodeValidator is a validator for the "hashedAuthCode" field. It is called by the builders before save.
	HashedAuthCodeValidator func([]byte) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DownloadSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByValidFrom orders the results by the validFrom field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByValidUntil orders the results by the validUntil field.
func ByValidUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidUntil, opts...).ToFunc()
}

// ByUserAgent orders the results by the userAgent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByStashID orders the results by the stashID field.
func ByStashID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStashID, opts...).ToFunc()
}

// ByStashField orders the results by stash field.
func ByStashField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStashStep(), sql.OrderByField(field, opts...))
	}
}

// ByLoginAlertsCount orders the results by loginAlerts count.
func ByLoginAlertsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLoginAlertsStep(), opts...)
	}
}

// ByLoginAlerts orders the results by loginAlerts terms.
func ByLoginAlerts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLoginAlertsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStashStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StashInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StashTable, StashColumn),
	)
}
func newLoginAlertsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LoginAlertsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LoginAlertsTable, LoginAlertsColumn),
	)
}
