// Code generated by ent, DO NOT EDIT.

package downloadsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldCreatedAt, v))
}

// HashedAuthCode applies equality check predicate on the "hashedAuthCode" field. It's identical to HashedAuthCodeEQ.
func HashedAuthCode(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldHashedAuthCode, v))
}

// ValidFrom applies equality check predicate on the "validFrom" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldValidFrom, v))
}

// ValidUntil applies equality check predicate on the "validUntil" field. It's identical to ValidUntilEQ.
func ValidUntil(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldValidUntil, v))
}

// UserAgent applies equality check predicate on the "userAgent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldUserAgent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldIP, v))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldCreatedAt, v))
}

// HashedAuthCodeEQ applies the EQ predicate on the "hashedAuthCode" field.
func HashedAuthCodeEQ(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldHashedAuthCode, v))
}

// HashedAuthCodeNEQ applies the NEQ predicate on the "hashedAuthCode" field.
func HashedAuthCodeNEQ(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldHashedAuthCode, v))
}

// HashedAuthCodeIn applies the In predicate on the "hashedAuthCode" field.
func HashedAuthCodeIn(vs ...[]byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldHashedAuthCode, vs...))
}

// HashedAuthCodeNotIn applies the NotIn predicate on the "hashedAuthCode" field.
func HashedAuthCodeNotIn(vs ...[]byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldHashedAuthCode, vs...))
}

// HashedAuthCodeGT applies the GT predicate on the "hashedAuthCode" field.
func HashedAuthCodeGT(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldHashedAuthCode, v))
}

// HashedAuthCodeGTE applies the GTE predicate on the "hashedAuthCode" field.
func HashedAuthCodeGTE(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldHashedAuthCode, v))
}

// HashedAuthCodeLT applies the LT predicate on the "hashedAuthCode" field.
func HashedAuthCodeLT(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldHashedAuthCode, v))
}

// HashedAuthCodeLTE applies the LTE predicate on the "hashedAuthCode" field.
func HashedAuthCodeLTE(v []byte) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldHashedAuthCode, v))
}

// ValidFromEQ applies the EQ predicate on the "validFrom" field.
func ValidFromEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "validFrom" field.
func ValidFromNEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "validFrom" field.
func ValidFromIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "validFrom" field.
func ValidFromNotIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "validFrom" field.
func ValidFromGT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "validFrom" field.
func ValidFromGTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "validFrom" field.
func ValidFromLT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "validFrom" field.
func ValidFromLTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldValidFrom, v))
}

// ValidUntilEQ applies the EQ predicate on the "validUntil" field.
func ValidUntilEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldValidUntil, v))
}

// ValidUntilNEQ applies the NEQ predicate on the "validUntil" field.
func ValidUntilNEQ(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldValidUntil, v))
}

// ValidUntilIn applies the In predicate on the "validUntil" field.
func ValidUntilIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldValidUntil, vs...))
}

// ValidUntilNotIn applies the NotIn predicate on the "validUntil" field.
func ValidUntilNotIn(vs ...time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldValidUntil, vs...))
}

// ValidUntilGT applies the GT predicate on the "validUntil" field.
func ValidUntilGT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldValidUntil, v))
}

// ValidUntilGTE applies the GTE predicate on the "validUntil" field.
func ValidUntilGTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldValidUntil, v))
}

// ValidUntilLT applies the LT predicate on the "validUntil" field.
func ValidUntilLT(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldValidUntil, v))
}

// ValidUntilLTE applies the LTE predicate on the "validUntil" field.
func ValidUntilLTE(v time.Time) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldValidUntil, v))
}

// UserAgentEQ applies the EQ predicate on the "userAgent" field.
func UserAgentEQ(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "userAgent" field.
func UserAgentNEQ(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "userAgent" field.
func UserAgentIn(vs ...string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "userAgent" field.
func UserAgentNotIn(vs ...string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "userAgent" field.
func UserAgentGT(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "userAgent" field.
func UserAgentGTE(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "userAgent" field.
func UserAgentLT(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "userAgent" field.
func UserAgentLTE(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "userAgent" field.
func UserAgentContains(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "userAgent" field.
func UserAgentHasPrefix(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "userAgent" field.
func UserAgentHasSuffix(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "userAgent" field.
func UserAgentEqualFold(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "userAgent" field.
func UserAgentContainsFold(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldContainsFold(FieldIP, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.DownloadSession {
	return predicate.DownloadSession(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DownloadSession {
	return predicate.DownloadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DownloadSession {
	return predicate.DownloadSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLoginAlerts applies the HasEdge predicate on the "loginAlerts" edge.
func HasLoginAlerts() predicate.DownloadSession {
	return predicate.DownloadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LoginAlertsTable, LoginAlertsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLoginAlertsWith applies the HasEdge predicate on the "loginAlerts" edge with a given conditions (other predicates).
func HasLoginAlertsWith(preds ...predicate.LoginAlert) predicate.DownloadSession {
	return predicate.DownloadSession(func(s *sql.Selector) {
		step := newLoginAlertsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DownloadSession) predicate.DownloadSession {
	return predicate.DownloadSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DownloadSession) predicate.DownloadSession {
	return predicate.DownloadSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DownloadSession) predicate.DownloadSession {
	return predicate.DownloadSession(sql.NotPredicates(p))
}
