// Code generated by ent, DO NOT EDIT.

package passkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the passkey type in the database.
	Label = "passkey"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAllowSudo holds the string denoting the allowsudo field in the database.
	FieldAllowSudo = "allow_sudo"
	// FieldCredentialID holds the string denoting the credentialid field in the database.
	FieldCredentialID = "credential_id"
	// FieldCredential holds the string denoting the credential field in the database.
	FieldCredential = "credential"
	// FieldIsSecondGroup holds the string denoting the issecondgroup field in the database.
	FieldIsSecondGroup = "is_second_group"
	// FieldLastUsedAt holds the string denoting the lastusedat field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeElevatedSessions holds the string denoting the elevatedsessions edge name in mutations.
	EdgeElevatedSessions = "elevatedSessions"
	// Table holds the table name of the passkey in the database.
	Table = "passkeys"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "passkeys"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "passkey_id"
	// ElevatedSessionsTable is the table that holds the elevatedSessions relation/edge.
	ElevatedSessionsTable = "sessions"
	// ElevatedSessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	ElevatedSessionsInverseTable = "sessions"
	// ElevatedSessionsColumn is the table column denoting the elevatedSessions relation/edge.
	ElevatedSessionsColumn = "elevation_passkey_id"
)

// Columns holds all SQL columns for passkey fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldAllowSudo,
	FieldCredentialID,
	FieldCredential,
	FieldIsSecondGroup,
	FieldLastUsedAt,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CredentialIDValidator is a validator for the "credentialID" field. It is called by the builders before save.
	CredentialIDValidator func([]byte) error
	// DefaultIsSecondGroup holds the default value on creation for the "isSecondGroup" field.
	DefaultIsSecondGroup bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
	// ValueScanner of all Passkey fields.
	ValueScanner struct {
		Credential field.TypeValueScanner[webauthn.Credential]
	}
)

// OrderOption defines the ordering options for the Passkey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAllowSudo orders the results by the allowSudo field.
func ByAllowSudo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowSudo, opts...).ToFunc()
}

// ByIsSecondGroup orders the results by the isSecondGroup field.
func ByIsSecondGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSecondGroup, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the lastUsedAt field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByUserID orders the results by the userID field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByElevatedSessionsCount orders the results by elevatedSessions count.
func ByElevatedSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newElevatedSessionsStep(), opts...)
	}
}

// ByElevatedSessions orders the results by elevatedSessions terms.
func ByElevatedSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newElevatedSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newElevatedSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ElevatedSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ElevatedSessionsTable, ElevatedSessionsColumn),
	)
}
