// Code generated by ent, DO NOT EDIT.

package passkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldName, v))
}

// CredentialID applies equality check predicate on the "credentialID" field. It's identical to CredentialIDEQ.
func CredentialID(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldCredentialID, v))
}

// PublicKey applies equality check predicate on the "publicKey" field. It's identical to PublicKeyEQ.
func PublicKey(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldPublicKey, v))
}

// Aaguid applies equality check predicate on the "aaguid" field. It's identical to AaguidEQ.
func Aaguid(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldAaguid, v))
}

// SignCount applies equality check predicate on the "signCount" field. It's identical to SignCountEQ.
func SignCount(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldSignCount, v))
}

// IsSecondFactor applies equality check predicate on the "isSecondFactor" field. It's identical to IsSecondFactorEQ.
func IsSecondFactor(v bool) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldIsSecondFactor, v))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Passkey {
	return predicate.Passkey(sql.FieldContainsFold(FieldName, v))
}

// CredentialIDEQ applies the EQ predicate on the "credentialID" field.
func CredentialIDEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credentialID" field.
func CredentialIDNEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credentialID" field.
func CredentialIDIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credentialID" field.
func CredentialIDNotIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credentialID" field.
func CredentialIDGT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credentialID" field.
func CredentialIDGTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credentialID" field.
func CredentialIDLT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credentialID" field.
func CredentialIDLTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldCredentialID, v))
}

// PublicKeyEQ applies the EQ predicate on the "publicKey" field.
func PublicKeyEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "publicKey" field.
func PublicKeyNEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "publicKey" field.
func PublicKeyIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "publicKey" field.
func PublicKeyNotIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "publicKey" field.
func PublicKeyGT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "publicKey" field.
func PublicKeyGTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "publicKey" field.
func PublicKeyLT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "publicKey" field.
func PublicKeyLTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldPublicKey, v))
}

// AaguidEQ applies the EQ predicate on the "aaguid" field.
func AaguidEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldAaguid, v))
}

// AaguidNEQ applies the NEQ predicate on the "aaguid" field.
func AaguidNEQ(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldAaguid, v))
}

// AaguidIn applies the In predicate on the "aaguid" field.
func AaguidIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldAaguid, vs...))
}

// AaguidNotIn applies the NotIn predicate on the "aaguid" field.
func AaguidNotIn(vs ...[]byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldAaguid, vs...))
}

// AaguidGT applies the GT predicate on the "aaguid" field.
func AaguidGT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldAaguid, v))
}

// AaguidGTE applies the GTE predicate on the "aaguid" field.
func AaguidGTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldAaguid, v))
}

// AaguidLT applies the LT predicate on the "aaguid" field.
func AaguidLT(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldAaguid, v))
}

// AaguidLTE applies the LTE predicate on the "aaguid" field.
func AaguidLTE(v []byte) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldAaguid, v))
}

// SignCountEQ applies the EQ predicate on the "signCount" field.
func SignCountEQ(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldSignCount, v))
}

// SignCountNEQ applies the NEQ predicate on the "signCount" field.
func SignCountNEQ(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldSignCount, v))
}

// SignCountIn applies the In predicate on the "signCount" field.
func SignCountIn(vs ...uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldSignCount, vs...))
}

// SignCountNotIn applies the NotIn predicate on the "signCount" field.
func SignCountNotIn(vs ...uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldSignCount, vs...))
}

// SignCountGT applies the GT predicate on the "signCount" field.
func SignCountGT(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldGT(FieldSignCount, v))
}

// SignCountGTE applies the GTE predicate on the "signCount" field.
func SignCountGTE(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldGTE(FieldSignCount, v))
}

// SignCountLT applies the LT predicate on the "signCount" field.
func SignCountLT(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldLT(FieldSignCount, v))
}

// SignCountLTE applies the LTE predicate on the "signCount" field.
func SignCountLTE(v uint32) predicate.Passkey {
	return predicate.Passkey(sql.FieldLTE(FieldSignCount, v))
}

// IsSecondFactorEQ applies the EQ predicate on the "isSecondFactor" field.
func IsSecondFactorEQ(v bool) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldIsSecondFactor, v))
}

// IsSecondFactorNEQ applies the NEQ predicate on the "isSecondFactor" field.
func IsSecondFactorNEQ(v bool) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldIsSecondFactor, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Passkey {
	return predicate.Passkey(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Passkey {
	return predicate.Passkey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Passkey {
	return predicate.Passkey(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Passkey) predicate.Passkey {
	return predicate.Passkey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Passkey) predicate.Passkey {
	return predicate.Passkey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Passkey) predicate.Passkey {
	return predicate.Passkey(sql.NotPredicates(p))
}
