// Code generated by ent, DO NOT EDIT.

package invite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldEmail, v))
}

// HashedCode applies equality check predicate on the "hashedCode" field. It's identical to HashedCodeEQ.
func HashedCode(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldHashedCode, v))
}

// ExpiresAt applies equality check predicate on the "expiresAt" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldExpiresAt, v))
}

// PendingUserID applies equality check predicate on the "pendingUserID" field. It's identical to PendingUserIDEQ.
func PendingUserID(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldPendingUserID, v))
}

// WebAuthnChallenge applies equality check predicate on the "webAuthnChallenge" field. It's identical to WebAuthnChallengeEQ.
func WebAuthnChallenge(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldWebAuthnChallenge, v))
}

// ChallengeExpiresAt applies equality check predicate on the "challengeExpiresAt" field. It's identical to ChallengeExpiresAtEQ.
func ChallengeExpiresAt(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldChallengeExpiresAt, v))
}

// UserAgent applies equality check predicate on the "userAgent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUserAgent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldIP, v))
}

// UserID applies equality check predicate on the "userID" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContainsFold(FieldEmail, v))
}

// HashedCodeEQ applies the EQ predicate on the "hashedCode" field.
func HashedCodeEQ(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldHashedCode, v))
}

// HashedCodeNEQ applies the NEQ predicate on the "hashedCode" field.
func HashedCodeNEQ(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldHashedCode, v))
}

// HashedCodeIn applies the In predicate on the "hashedCode" field.
func HashedCodeIn(vs ...[]byte) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldHashedCode, vs...))
}

// HashedCodeNotIn applies the NotIn predicate on the "hashedCode" field.
func HashedCodeNotIn(vs ...[]byte) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldHashedCode, vs...))
}

// HashedCodeGT applies the GT predicate on the "hashedCode" field.
func HashedCodeGT(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldHashedCode, v))
}

// HashedCodeGTE applies the GTE predicate on the "hashedCode" field.
func HashedCodeGTE(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldHashedCode, v))
}

// HashedCodeLT applies the LT predicate on the "hashedCode" field.
func HashedCodeLT(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldHashedCode, v))
}

// HashedCodeLTE applies the LTE predicate on the "hashedCode" field.
func HashedCodeLTE(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldHashedCode, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expiresAt" field.
func ExpiresAtEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expiresAt" field.
func ExpiresAtNEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expiresAt" field.
func ExpiresAtIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expiresAt" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expiresAt" field.
func ExpiresAtGT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expiresAt" field.
func ExpiresAtGTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expiresAt" field.
func ExpiresAtLT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expiresAt" field.
func ExpiresAtLTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiredReasonEQ applies the EQ predicate on the "expiredReason" field.
func ExpiredReasonEQ(v ExpiredReason) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldExpiredReason, v))
}

// ExpiredReasonNEQ applies the NEQ predicate on the "expiredReason" field.
func ExpiredReasonNEQ(v ExpiredReason) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldExpiredReason, v))
}

// ExpiredReasonIn applies the In predicate on the "expiredReason" field.
func ExpiredReasonIn(vs ...ExpiredReason) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldExpiredReason, vs...))
}

// ExpiredReasonNotIn applies the NotIn predicate on the "expiredReason" field.
func ExpiredReasonNotIn(vs ...ExpiredReason) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldExpiredReason, vs...))
}

// ExpiredReasonIsNil applies the IsNil predicate on the "expiredReason" field.
func ExpiredReasonIsNil() predicate.Invite {
	return predicate.Invite(sql.FieldIsNull(FieldExpiredReason))
}

// ExpiredReasonNotNil applies the NotNil predicate on the "expiredReason" field.
func ExpiredReasonNotNil() predicate.Invite {
	return predicate.Invite(sql.FieldNotNull(FieldExpiredReason))
}

// PendingUserIDEQ applies the EQ predicate on the "pendingUserID" field.
func PendingUserIDEQ(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldPendingUserID, v))
}

// PendingUserIDNEQ applies the NEQ predicate on the "pendingUserID" field.
func PendingUserIDNEQ(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldPendingUserID, v))
}

// PendingUserIDIn applies the In predicate on the "pendingUserID" field.
func PendingUserIDIn(vs ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldPendingUserID, vs...))
}

// PendingUserIDNotIn applies the NotIn predicate on the "pendingUserID" field.
func PendingUserIDNotIn(vs ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldPendingUserID, vs...))
}

// PendingUserIDGT applies the GT predicate on the "pendingUserID" field.
func PendingUserIDGT(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldPendingUserID, v))
}

// PendingUserIDGTE applies the GTE predicate on the "pendingUserID" field.
func PendingUserIDGTE(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldPendingUserID, v))
}

// PendingUserIDLT applies the LT predicate on the "pendingUserID" field.
func PendingUserIDLT(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldPendingUserID, v))
}

// PendingUserIDLTE applies the LTE predicate on the "pendingUserID" field.
func PendingUserIDLTE(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldPendingUserID, v))
}

// PendingUserIDIsNil applies the IsNil predicate on the "pendingUserID" field.
func PendingUserIDIsNil() predicate.Invite {
	return predicate.Invite(sql.FieldIsNull(FieldPendingUserID))
}

// PendingUserIDNotNil applies the NotNil predicate on the "pendingUserID" field.
func PendingUserIDNotNil() predicate.Invite {
	return predicate.Invite(sql.FieldNotNull(FieldPendingUserID))
}

// WebAuthnChallengeEQ applies the EQ predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeEQ(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeNEQ applies the NEQ predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeNEQ(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeIn applies the In predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeIn(vs ...[]byte) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldWebAuthnChallenge, vs...))
}

// WebAuthnChallengeNotIn applies the NotIn predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeNotIn(vs ...[]byte) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldWebAuthnChallenge, vs...))
}

// WebAuthnChallengeGT applies the GT predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeGT(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeGTE applies the GTE predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeGTE(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeLT applies the LT predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeLT(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeLTE applies the LTE predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeLTE(v []byte) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldWebAuthnChallenge, v))
}

// WebAuthnChallengeIsNil applies the IsNil predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeIsNil() predicate.Invite {
	return predicate.Invite(sql.FieldIsNull(FieldWebAuthnChallenge))
}

// WebAuthnChallengeNotNil applies the NotNil predicate on the "webAuthnChallenge" field.
func WebAuthnChallengeNotNil() predicate.Invite {
	return predicate.Invite(sql.FieldNotNull(FieldWebAuthnChallenge))
}

// ChallengeExpiresAtEQ applies the EQ predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtNEQ applies the NEQ predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtNEQ(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtIn applies the In predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldChallengeExpiresAt, vs...))
}

// ChallengeExpiresAtNotIn applies the NotIn predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtNotIn(vs ...time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldChallengeExpiresAt, vs...))
}

// ChallengeExpiresAtGT applies the GT predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtGT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtGTE applies the GTE predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtGTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtLT applies the LT predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtLT(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtLTE applies the LTE predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtLTE(v time.Time) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldChallengeExpiresAt, v))
}

// ChallengeExpiresAtIsNil applies the IsNil predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtIsNil() predicate.Invite {
	return predicate.Invite(sql.FieldIsNull(FieldChallengeExpiresAt))
}

// ChallengeExpiresAtNotNil applies the NotNil predicate on the "challengeExpiresAt" field.
func ChallengeExpiresAtNotNil() predicate.Invite {
	return predicate.Invite(sql.FieldNotNull(FieldChallengeExpiresAt))
}

// UserAgentEQ applies the EQ predicate on the "userAgent" field.
func UserAgentEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "userAgent" field.
func UserAgentNEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "userAgent" field.
func UserAgentIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "userAgent" field.
func UserAgentNotIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "userAgent" field.
func UserAgentGT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "userAgent" field.
func UserAgentGTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "userAgent" field.
func UserAgentLT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "userAgent" field.
func UserAgentLTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "userAgent" field.
func UserAgentContains(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "userAgent" field.
func UserAgentHasPrefix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "userAgent" field.
func UserAgentHasSuffix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "userAgent" field.
func UserAgentEqualFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "userAgent" field.
func UserAgentContainsFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Invite {
	return predicate.Invite(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Invite {
	return predicate.Invite(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Invite {
	return predicate.Invite(sql.FieldContainsFold(FieldIP, v))
}

// UserIDEQ applies the EQ predicate on the "userID" field.
func UserIDEQ(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "userID" field.
func UserIDNEQ(v uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "userID" field.
func UserIDIn(vs ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "userID" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Invite {
	return predicate.Invite(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "userID" field.
func UserIDIsNil() predicate.Invite {
	return predicate.Invite(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "userID" field.
func UserIDNotNil() predicate.Invite {
	return predicate.Invite(sql.FieldNotNull(FieldUserID))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Invite {
	return predicate.Invite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Invite {
	return predicate.Invite(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Invite) predicate.Invite {
	return predicate.Invite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Invite) predicate.Invite {
	return predicate.Invite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Invite) predicate.Invite {
	return predicate.Invite(sql.NotPredicates(p))
}
