// Code generated by ent, DO NOT EDIT.

package loginalert

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the loginalert type in the database.
	Label = "login_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSentAt holds the string denoting the sentat field in the database.
	FieldSentAt = "sent_at"
	// FieldConfirmed holds the string denoting the confirmed field in the database.
	FieldConfirmed = "confirmed"
	// FieldDownloadSessionID holds the string denoting the downloadsessionid field in the database.
	FieldDownloadSessionID = "download_session_id"
	// EdgeDownloadSession holds the string denoting the downloadsession edge name in mutations.
	EdgeDownloadSession = "downloadSession"
	// Table holds the table name of the loginalert in the database.
	Table = "login_alerts"
	// DownloadSessionTable is the table that holds the downloadSession relation/edge.
	DownloadSessionTable = "login_alerts"
	// DownloadSessionInverseTable is the table name for the DownloadSession entity.
	// It exists in this package in order to avoid circular dependency with the "downloadsession" package.
	DownloadSessionInverseTable = "download_sessions"
	// DownloadSessionColumn is the table column denoting the downloadSession relation/edge.
	DownloadSessionColumn = "download_session_id"
)

// Columns holds all SQL columns for loginalert fields.
var Columns = []string{
	FieldID,
	FieldSentAt,
	FieldConfirmed,
	FieldDownloadSessionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LoginAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySentAt orders the results by the sentAt field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}

// ByConfirmed orders the results by the confirmed field.
func ByConfirmed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmed, opts...).ToFunc()
}

// ByDownloadSessionID orders the results by the downloadSessionID field.
func ByDownloadSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadSessionID, opts...).ToFunc()
}

// ByDownloadSessionField orders the results by downloadSession field.
func ByDownloadSessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newDownloadSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadSessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DownloadSessionTable, DownloadSessionColumn),
	)
}
