// Code generated by ent, DO NOT EDIT.

package loginalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the loginalert type in the database.
	Label = "login_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSentAt holds the string denoting the sentat field in the database.
	FieldSentAt = "sent_at"
	// FieldConfirmed holds the string denoting the confirmed field in the database.
	FieldConfirmed = "confirmed"
	// FieldDownloadSessionID holds the string denoting the downloadsessionid field in the database.
	FieldDownloadSessionID = "download_session_id"
	// FieldUserMessengerID holds the string denoting the usermessengerid field in the database.
	FieldUserMessengerID = "user_messenger_id"
	// EdgeDownloadSession holds the string denoting the downloadsession edge name in mutations.
	EdgeDownloadSession = "downloadSession"
	// EdgeUserMessenger holds the string denoting the usermessenger edge name in mutations.
	EdgeUserMessenger = "userMessenger"
	// Table holds the table name of the loginalert in the database.
	Table = "login_alerts"
	// DownloadSessionTable is the table that holds the downloadSession relation/edge.
	DownloadSessionTable = "login_alerts"
	// DownloadSessionInverseTable is the table name for the DownloadSession entity.
	// It exists in this package in order to avoid circular dependency with the "downloadsession" package.
	DownloadSessionInverseTable = "download_sessions"
	// DownloadSessionColumn is the table column denoting the downloadSession relation/edge.
	DownloadSessionColumn = "download_session_id"
	// UserMessengerTable is the table that holds the userMessenger relation/edge.
	UserMessengerTable = "login_alerts"
	// UserMessengerInverseTable is the table name for the UserMessenger entity.
	// It exists in this package in order to avoid circular dependency with the "usermessenger" package.
	UserMessengerInverseTable = "user_messengers"
	// UserMessengerColumn is the table column denoting the userMessenger relation/edge.
	UserMessengerColumn = "user_messenger_id"
)

// Columns holds all SQL columns for loginalert fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSentAt,
	FieldConfirmed,
	FieldDownloadSessionID,
	FieldUserMessengerID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LoginAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySentAt orders the results by the sentAt field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}

// ByConfirmed orders the results by the confirmed field.
func ByConfirmed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmed, opts...).ToFunc()
}

// ByDownloadSessionID orders the results by the downloadSessionID field.
func ByDownloadSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadSessionID, opts...).ToFunc()
}

// ByUserMessengerID orders the results by the userMessengerID field.
func ByUserMessengerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserMessengerID, opts...).ToFunc()
}

// ByDownloadSessionField orders the results by downloadSession field.
func ByDownloadSessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadSessionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserMessengerField orders the results by userMessenger field.
func ByUserMessengerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserMessengerStep(), sql.OrderByField(field, opts...))
	}
}
func newDownloadSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadSessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DownloadSessionTable, DownloadSessionColumn),
	)
}
func newUserMessengerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserMessengerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserMessengerTable, UserMessengerColumn),
	)
}
