// Code generated by ent, DO NOT EDIT.

package loginalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldID, id))
}

// SentAt applies equality check predicate on the "sentAt" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSentAt, v))
}

// Confirmed applies equality check predicate on the "confirmed" field. It's identical to ConfirmedEQ.
func Confirmed(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// DownloadSessionID applies equality check predicate on the "downloadSessionID" field. It's identical to DownloadSessionIDEQ.
func DownloadSessionID(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldDownloadSessionID, v))
}

// UserMessengerID applies equality check predicate on the "userMessengerID" field. It's identical to UserMessengerIDEQ.
func UserMessengerID(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldUserMessengerID, v))
}

// SentAtEQ applies the EQ predicate on the "sentAt" field.
func SentAtEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sentAt" field.
func SentAtNEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sentAt" field.
func SentAtIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sentAt" field.
func SentAtNotIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sentAt" field.
func SentAtGT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sentAt" field.
func SentAtGTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sentAt" field.
func SentAtLT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sentAt" field.
func SentAtLTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldSentAt, v))
}

// ConfirmedEQ applies the EQ predicate on the "confirmed" field.
func ConfirmedEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// ConfirmedNEQ applies the NEQ predicate on the "confirmed" field.
func ConfirmedNEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldConfirmed, v))
}

// DownloadSessionIDEQ applies the EQ predicate on the "downloadSessionID" field.
func DownloadSessionIDEQ(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldDownloadSessionID, v))
}

// DownloadSessionIDNEQ applies the NEQ predicate on the "downloadSessionID" field.
func DownloadSessionIDNEQ(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldDownloadSessionID, v))
}

// DownloadSessionIDIn applies the In predicate on the "downloadSessionID" field.
func DownloadSessionIDIn(vs ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldDownloadSessionID, vs...))
}

// DownloadSessionIDNotIn applies the NotIn predicate on the "downloadSessionID" field.
func DownloadSessionIDNotIn(vs ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldDownloadSessionID, vs...))
}

// UserMessengerIDEQ applies the EQ predicate on the "userMessengerID" field.
func UserMessengerIDEQ(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldUserMessengerID, v))
}

// UserMessengerIDNEQ applies the NEQ predicate on the "userMessengerID" field.
func UserMessengerIDNEQ(v uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldUserMessengerID, v))
}

// UserMessengerIDIn applies the In predicate on the "userMessengerID" field.
func UserMessengerIDIn(vs ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldUserMessengerID, vs...))
}

// UserMessengerIDNotIn applies the NotIn predicate on the "userMessengerID" field.
func UserMessengerIDNotIn(vs ...uuid.UUID) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldUserMessengerID, vs...))
}

// HasDownloadSession applies the HasEdge predicate on the "downloadSession" edge.
func HasDownloadSession() predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DownloadSessionTable, DownloadSessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDownloadSessionWith applies the HasEdge predicate on the "downloadSession" edge with a given conditions (other predicates).
func HasDownloadSessionWith(preds ...predicate.DownloadSession) predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := newDownloadSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserMessenger applies the HasEdge predicate on the "userMessenger" edge.
func HasUserMessenger() predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserMessengerTable, UserMessengerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserMessengerWith applies the HasEdge predicate on the "userMessenger" edge with a given conditions (other predicates).
func HasUserMessengerWith(preds ...predicate.UserMessenger) predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := newUserMessengerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.NotPredicates(p))
}
